package com.zoho.charm.project.utils.encoder;

public interface EncodingConstants {

	// Set this to false if you don't want to resolve the issues that are'nt
	// resolved automatically during runtime.
	public static final Boolean ENABLE_SEMI_AUTOMATED_ENCODING = Boolean.TRUE;

	// Set this to true to print the options every time a input is asked
	public static final Boolean SHOULD_PRINT_ENCODING_OPTIONS = Boolean.FALSE;

	// Set this to true if you want an confirmation before writing a manually
	// encoded line
	public static final Boolean IS_CHECK_REQUIRED = Boolean.FALSE;

	// Should we print the list of ignored lines , if so set true
	public static final Boolean PRINT_IGNORED = Boolean.FALSE;

	// The file name would contain the remaining path
	public static final String WORKSPACE_LOCATION = "/home/local/ZOHOCORP/aravind-5939/My_Branch/charmehr_old_UI/";

	// Create this directory , or an exception would be thrown
	public static final String OUTPUT_FILES_FOLDER = "/home/local/ZOHOCORP/aravind-5939/Desktop/Encoding/";

	//If you wish to give the file names in a file rather than the array specify it here
	//public static final String FILE_NAMES_LOCATION = OUTPUT_FILES_FOLDER.concat("fileNames.txt");
	//public static final String FILE_NAMES_LOCATION = OUTPUT_FILES_FOLDER.concat("RamanathanFiles.txt");
	public static final String FILE_NAMES_LOCATION = OUTPUT_FILES_FOLDER.concat("allFiles.txt");
	// Copy your file names from the Excel sheet
	// Use find and replace to get this structure
	// Find webapps/ and replace with "webapps/
	// Find .jsp and replace with .jsp",
	// Remove the comma in the last jsp and paste the contens b/w the braces
	public static String FILE_NAMES[] = {
			"webapps/charm/physician/mypatients/encounter/PersonalDetailQuestionnaire.jsp",
			"webapps/charm/physician/mypatients/encounter/PHRSharedData.jsp",
			"webapps/charm/physician/mypatients/encounter/PhysicalExamination.jsp",
			"webapps/charm/physician/mypatients/encounter/PhysicianNotes.jsp",
			"webapps/charm/physician/mypatients/encounter/PhysicianTranscriptsList.jsp",
			"webapps/charm/physician/mypatients/encounter/PhysicianTranscriptsView.jsp",
			"webapps/charm/physician/mypatients/encounter/PlanOfCare.jsp",
			"webapps/charm/physician/mypatients/encounter/PrescriptionHistory.jsp",
			"webapps/charm/physician/mypatients/encounter/Prescriptions.jsp",
			"webapps/charm/physician/mypatients/encounter/PreviewBriefEncounter.jsp",
			"webapps/charm/physician/mypatients/encounter/PreviewEncounter.jsp",
			"webapps/charm/physician/mypatients/encounter/PreviewQuickEncounter.jsp",
			"webapps/charm/physician/mypatients/encounter/PrintOrderImages.jsp",
			"webapps/charm/physician/mypatients/encounter/ProcedureHistory.jsp",
			"webapps/charm/physician/mypatients/encounter/PsychotherapyNotes.jsp",
			"webapps/charm/physician/mypatients/encounter/QualityMeasures.jsp",
			"webapps/charm/physician/mypatients/encounter/Questionnaire.jsp",
			"webapps/charm/physician/mypatients/encounter/QuestionnaireTemplatesEntries.jsp",
			"webapps/charm/physician/mypatients/encounter/QuestionnaireTemplatesView.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterDiagnosis.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterHandouts.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterImages.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterInjectionsIVT.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterLabs.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterPrescriptions.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickEncounterSupplements.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickMessage.jsp",
			"webapps/charm/physician/mypatients/encounter/QuickPrescription.jsp",
			"webapps/charm/physician/mypatients/encounter/ReferralsContainer.jsp",
			"webapps/charm/physician/mypatients/encounter/ReferralsList.jsp",
			"webapps/charm/physician/mypatients/encounter/ReferralTemplateView.jsp",
			"webapps/charm/physician/mypatients/encounter/RepeatEncounter.jsp",
			"webapps/charm/physician/mypatients/encounter/RepeatSOAPEncounter.jsp",
			"webapps/charm/physician/mypatients/encounter/reports-fax.jsp",
			"webapps/charm/physician/mypatients/encounter/SelfNotes.jsp",
			"webapps/charm/physician/mypatients/encounter/ShowEditPlanOfCare.jsp",
			"webapps/charm/physician/mypatients/encounter/ShowEncounterHealthVitals.jsp",
			"webapps/charm/physician/mypatients/encounter/ShowImageTests.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/QuickEncounterHandouts.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPContainer.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPContent.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPDiagnosisEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPImage.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPImage_InnerNew.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPImageAnnotationEntry_InnerNew.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPImageAnnotationEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPImageAnnotations.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPImageEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPLabelEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPLabelEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPLabRecordEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPOptionsEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPOptionsEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSimpleNoteEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSimpleNoteEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSimpleTableEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSimpleTableEntry_new.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSimpleTextEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSimpleTextEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSlideEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPSlideEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTabulerContent.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTempImageEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTempImageEntry_new.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTemplateChooser.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTextBoxEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTextEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPTextEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPWidgetContent.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPWidgetHeader.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPYesorNoEntry.jsp",
			"webapps/charm/physician/mypatients/encounter/soapnotes/SOAPYesorNoEntry_New.jsp",
			"webapps/charm/physician/mypatients/encounter/StartEncounter.jsp",
			"webapps/charm/physician/mypatients/encounter/SubjectiveNotes.jsp",
			"webapps/charm/physician/mypatients/encounter/SuperbillsList.jsp",
			"webapps/charm/physician/mypatients/encounter/SupplementsHistory.jsp",
			"webapps/charm/physician/mypatients/encounter/TreatmentNotes.jsp",
			"webapps/charm/physician/mypatients/encounter/VaccineTemplateInner.jsp",
			"webapps/charm/physician/mypatients/encounter/VaccineTemplateLotDetails.jsp",
			"webapps/charm/physician/mypatients/encounter/ViewAttachments.jsp",
			"webapps/charm/physician/mypatients/encounter/ViewFaceSheet.jsp",
			"webapps/charm/physician/mypatients/FutureAppointments.jsp",
			"webapps/charm/physician/mypatients/MapPatient.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/AddLabOrderUI.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/AddNewLabItem.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/AddNewRecord.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/AssociateMedicalRecord.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/CompleteLabRecordList.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/DirectLabOrderInstantAdd.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/DirectNewLabOrder.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/EditLabParam.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/EnterMedicalRecord.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/EnterMedicalRecordInfo.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/EnterRecordParameters.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/FaxLabOrderDialog.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/FetchOrderedLabs.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/ImportPdfForLabOrder.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/LabOrdersList.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/LabResult.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/LabResultList.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/MedicalRecord.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/MedicalRecordDetail.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/MedicalRecordValues.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/MedicalRecordValuesParent.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/MessageFromPhysician.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/NewTabMedicalRecordDetail.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/NewTabRecordPdfContent.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/OrderSummary.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/PrintLabOrderDialog.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/RecordPdfContent.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/SharedPatientMessage.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/ShowAccuDrawDetails.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/ShowGraph.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/ShowGraphOuter.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/ShowIndiaLabs.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/ShowNewLabOrders.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/SinceLastVisit.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/SinceLastVisitEncounter.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/TestResult.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/VirtualTree.jsp",
			"webapps/charm/physician/mypatients/medicalrecord/VirtualTreePdfContent.jsp",
			"webapps/charm/physician/mypatients/MessageContent.jsp",
			"webapps/charm/physician/mypatients/MessagesList.jsp",
			"webapps/charm/physician/mypatients/MessagesView.jsp",
			"webapps/charm/physician/mypatients/NewTabComposeMessage.jsp",
			"webapps/charm/physician/mypatients/observations/ClinicalObservations.jsp",
			"webapps/charm/physician/mypatients/observations/ClinicalObservationsList.jsp",
			"webapps/charm/physician/mypatients/observations/ClinicalObservationsView.jsp",
			"webapps/charm/physician/mypatients/observations/Observations.jsp",
			"webapps/charm/physician/mypatients/PastAppointments.jsp",
			"webapps/charm/physician/mypatients/pastdata/AssessmentNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/AssessmentNotesView.jsp",
			"webapps/charm/physician/mypatients/pastdata/HistoryNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/HistoryNotesView.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastData.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastDataPrescriptions.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastMedicalNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastMedicalNotesView.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastPrescriptionValue.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastReviewSystemList.jsp",
			"webapps/charm/physician/mypatients/pastdata/PastReviewSystemView.jsp",
			"webapps/charm/physician/mypatients/pastdata/PatientNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/PatientNotesView.jsp",
			"webapps/charm/physician/mypatients/pastdata/PhysicalExaminationList.jsp",
			"webapps/charm/physician/mypatients/pastdata/PhysicalExaminationView.jsp",
			"webapps/charm/physician/mypatients/pastdata/ProblemNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/ProblemNotesView.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfAssessmentNotse.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfClinicalObservation.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfPatientNotes.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfPhysicalExamination.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfProblemNotes.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfSelfNotse.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchListOfTreatmentNotes.jsp",
			"webapps/charm/physician/mypatients/pastdata/SearchPastData.jsp",
			"webapps/charm/physician/mypatients/pastdata/SelfNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/SelfNotesView.jsp",
			"webapps/charm/physician/mypatients/pastdata/TreatmentNotesList.jsp",
			"webapps/charm/physician/mypatients/pastdata/TreatmentNotesView.jsp",
			"webapps/charm/physician/mypatients/PatientListUpload.jsp",
			"webapps/charm/physician/mypatients/PatientView.jsp",
			"webapps/charm/physician/mypatients/PaymentNotifications.jsp",
			"webapps/charm/physician/mypatients/PdfUpload.jsp",
			"webapps/charm/physician/mypatients/PersonalDetails.jsp",
			"webapps/charm/physician/mypatients/PharmacyDetails.jsp",
			"webapps/charm/physician/mypatients/PharmacyDetails_Rx.jsp",
			"webapps/charm/physician/mypatients/PharmacyDetails_View.jsp",
			"webapps/charm/physician/mypatients/PhotoUpload.jsp", "webapps/charm/physician/mypatients/PickMembers.jsp",
			"webapps/charm/physician/mypatients/recommendations/ActivePrescriptions.jsp",
			"webapps/charm/physician/mypatients/recommendations/ActiveSupplements.jsp",
			"webapps/charm/physician/mypatients/recommendations/AddSupplementRecommendation.jsp",
			"webapps/charm/physician/mypatients/recommendations/CallInRx.jsp",
			"webapps/charm/physician/mypatients/recommendations/DietLifestyleTemplateEntriesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/DietLifestyleTemplatesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/EditPrescriptionRecommendations.jsp",
			"webapps/charm/physician/mypatients/recommendations/EditRationale.jsp",
			"webapps/charm/physician/mypatients/recommendations/EditSupplementRecommendations.jsp",
			"webapps/charm/physician/mypatients/recommendations/FetchOrderedLabs.jsp",
			"webapps/charm/physician/mypatients/recommendations/ImageOrders.jsp",
			"webapps/charm/physician/mypatients/recommendations/ImageTemplateEntriesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/ImageTemplatesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/LabTemplateEntriesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/LabTemplatesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/OpenDietRecommendations.jsp",
			"webapps/charm/physician/mypatients/recommendations/OpenLifeStyleRecommendations.jsp",
			"webapps/charm/physician/mypatients/recommendations/PastOrderedLabs.jsp",
			"webapps/charm/physician/mypatients/recommendations/PastOrderedLabsValues.jsp",
			"webapps/charm/physician/mypatients/recommendations/PrescriptionTemplatesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/PrescrTemplateEntriesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/Recommendations.jsp",
			"webapps/charm/physician/mypatients/recommendations/RecommendedPrescriptions.jsp",
			"webapps/charm/physician/mypatients/recommendations/RecommendedSupplements.jsp",
			"webapps/charm/physician/mypatients/recommendations/SearchPastOrderedLabs.jsp",
			"webapps/charm/physician/mypatients/recommendations/SupplementTemplatesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/SupplmTemplateEntriesView.jsp",
			"webapps/charm/physician/mypatients/recommendations/Type1_EditPrescription.jsp",
			"webapps/charm/physician/mypatients/recommendations/Type1_PrescrTemplateEntriesView.jsp",
			"webapps/charm/physician/mypatients/recordreview/ApprovalContainer.jsp",
			"webapps/charm/physician/mypatients/recordreview/BriefEncounterContent.jsp",
			"webapps/charm/physician/mypatients/recordreview/ConsultationHistory.jsp",
			"webapps/charm/physician/mypatients/recordreview/ConsultationPrintView.jsp",
			"webapps/charm/physician/mypatients/recordreview/Container.jsp",
			"webapps/charm/physician/mypatients/recordreview/EncounterWrapper.jsp",
			"webapps/charm/physician/mypatients/recordreview/History.jsp",
			"webapps/charm/physician/mypatients/recordreview/IntakeQuestionnaireView.jsp",
			"webapps/charm/physician/mypatients/recordreview/PatientBills.jsp",
			"webapps/charm/physician/mypatients/recordreview/PatientReports.jsp",
			"webapps/charm/physician/mypatients/recordreview/PrescriptionPrintView.jsp",
			"webapps/charm/physician/mypatients/recordreview/PreviewSOAPEncounter.jsp",
			"webapps/charm/physician/mypatients/recordreview/PrintImaging.jsp",
			"webapps/charm/physician/mypatients/recordreview/QuickEncounterContent.jsp",
			"webapps/charm/physician/mypatients/recordreview/QuickNotesHistory.jsp",
			"webapps/charm/physician/mypatients/recordreview/RearrangeIns.jsp",
			"webapps/charm/physician/mypatients/recordreview/SendMail.jsp",
			"webapps/charm/physician/mypatients/recordreview/UnsignConfirmation.jsp",
			"webapps/charm/physician/mypatients/recordreview/UploadPaperRecords.jsp",
			"webapps/charm/physician/mypatients/recordreview/ViewPaperRecord.jsp",
			"webapps/charm/physician/mypatients/recordreview/ViewPastEncounter.jsp",
			"webapps/charm/physician/mypatients/recordreview/ViewPastQuestionnaire.jsp",
			"webapps/charm/physician/mypatients/recordreview/ViewQuickNotes.jsp",
			"webapps/charm/physician/mypatients/recordreview/ViewRxRenewal.jsp",
			"webapps/charm/physician/mypatients/RxSig.jsp",
			"webapps/charm/physician/mypatients/ShowExportPatientsList.jsp",
			"webapps/charm/physician/mypatients/ShowGraph.jsp",
			"webapps/charm/physician/mypatients/ShowInsuranceParser.jsp",
			"webapps/charm/physician/mypatients/ShowMyPatients.jsp",
			"webapps/charm/physician/mypatients/ShowQuestionnaire.jsp",
			"webapps/charm/physician/mypatients/ShowReferralDialog.jsp",
			"webapps/charm/physician/mypatients/ShowUploadPatient.jsp",
			"webapps/charm/physician/mypatients/SMSContent.jsp", "webapps/charm/physician/mypatients/SMSList.jsp",
			"webapps/charm/physician/mypatients/StatusOfUploadPatient.jsp",
			"webapps/charm/physician/mypatients/StickyNotes.jsp", "webapps/charm/physician/mypatients/StickyView.jsp",
			"webapps/charm/physician/mypatients/TimelyAccess.jsp", "webapps/charm/physician/mypatients/VideoCall.jsp",
			"webapps/charm/physician/mypatients/ViewFaceSheet.jsp",
			"webapps/charm/physician/mypatients/ViewInsurance.jsp",
			"webapps/charm/physician/mypatients/ViewMyPatients.jsp",
			"webapps/charm/physician/mypatients/ViewPaymentNotification.jsp",
			"webapps/charm/physician/mypatients/VoiceSMSContent.jsp",
			"webapps/charm/physician/mypatients/VoiceSMSList.jsp",
			"webapps/charm/physician/onlinepayment/PatientOnlinePayment.jsp",
			"webapps/charm/physician/onlinepayment/ViewReceipt.jsp", "webapps/charm/physician/PhysicianMainLayout.jsp",
			"webapps/charm/physician/RBACError.jsp",
			"webapps/charm/physician/reference/InstitutionalClaimReference.jsp",
			"webapps/charm/physician/reference/ShowDrugDetails.jsp",
			"webapps/charm/physician/reference/ToolsContent.jsp", "webapps/charm/physician/reference/ToolsLayout.jsp",
			"webapps/charm/physician/reference/ToolsMain.jsp", "webapps/charm/physician/reports/CustomizedReports.jsp",
			"webapps/charm/physician/reports/CustomizedReportsPatients.jsp",
			"webapps/charm/physician/reports/DiagnosisDetailsReport.jsp",
			"webapps/charm/physician/reports/DiagnosisStatistics.jsp",
			"webapps/charm/physician/reports/DiagnosisStatisticsInner.jsp",
			"webapps/charm/physician/reports/GeneratedMeasureReports.jsp",
			"webapps/charm/physician/reports/GenerateMeaningfulUseReport.jsp",
			"webapps/charm/physician/reports/GenerateVaccinationReport.jsp",
			"webapps/charm/physician/reports/LabRecordsGraph.jsp",
			"webapps/charm/physician/reports/MeaningfulUseReport.jsp",
			"webapps/charm/physician/reports/MeaningfulUseReportInner.jsp",
			"webapps/charm/physician/reports/MeasureReportsView.jsp",
			"webapps/charm/physician/reports/MedicalRecordInterpretationReport.jsp",
			"webapps/charm/physician/reports/MedicalRecordParamsReport.jsp",
			"webapps/charm/physician/reports/MedicationStatistics.jsp",
			"webapps/charm/physician/reports/MedicationStatistiscInner.jsp",
			"webapps/charm/physician/reports/MedicationStatsInner.jsp",
			"webapps/charm/physician/reports/PatientFollowupNew.jsp",
			"webapps/charm/physician/reports/PatientListSatisfied.jsp",
			"webapps/charm/physician/reports/PatientRecall.jsp",
			"webapps/charm/physician/reports/PatientReminderDialog.jsp",
			"webapps/charm/physician/reports/PatientReminderFromFollowUp.jsp",
			"webapps/charm/physician/reports/PatientsByProvider.jsp",
			"webapps/charm/physician/reports/PatientsFlow.jsp", "webapps/charm/physician/reports/PatientStatistics.jsp",
			"webapps/charm/physician/reports/PatStatistics.jsp",
			"webapps/charm/physician/reports/PatStatisticsList.jsp", "webapps/charm/physician/reports/PhrPatients.jsp",
			"webapps/charm/physician/reports/PhrUsage.jsp", "webapps/charm/physician/reports/PracticeStatistics.jsp",
			"webapps/charm/physician/reports/PrescriptionDetails.jsp",
			"webapps/charm/physician/reports/ReportsLayout.jsp", "webapps/charm/physician/reports/StageOneReport.jsp",
			"webapps/charm/physician/reports/StageTwoReport.jsp",
			"webapps/charm/physician/reports/VaccinationReport.jsp",
			"webapps/charm/physician/reports/VaccineReportList.jsp",
			"webapps/charm/physician/reviews/ATECPracticeLayout.jsp",
			"webapps/charm/physician/reviews/ATECPracticeList.jsp",
			"webapps/charm/physician/reviews/ATECPracticeQuestions.jsp",
			"webapps/charm/physician/reviews/FinishedChartView.jsp", "webapps/charm/physician/reviews/ImportHL7.jsp",
			"webapps/charm/physician/reviews/InProgressChartView.jsp",
			"webapps/charm/physician/reviews/LabRecordView.jsp", "webapps/charm/physician/reviews/QuickMessage.jsp",
			"webapps/charm/physician/reviews/ReviewChartsLayout.jsp",
			"webapps/charm/physician/reviews/ReviewChartsLayoutDashboardHome.jsp",
			"webapps/charm/physician/reviews/ReviewChartsList.jsp",
			"webapps/charm/physician/reviews/ReviewChartsListHome.jsp",
			"webapps/charm/physician/reviews/ReviewLabsLayout.jsp",
			"webapps/charm/physician/reviews/ReviewLabsList.jsp", "webapps/charm/physician/reviews/ReviewReports.jsp",
			"webapps/charm/physician/reviews/ShareLabRecordDialog.jsp",
			"webapps/charm/physician/reviews/SignRecordConfirmation.jsp",
			"webapps/charm/physician/routing/EPrescribe.jsp", "webapps/charm/physician/routing/eRxMain.jsp",
			"webapps/charm/physician/routing/eRxMedications.jsp", "webapps/charm/physician/routing/Formulary.jsp",
			"webapps/charm/physician/routing/FormularyCoverage.jsp",
			"webapps/charm/physician/routing/FormularyStatus.jsp", "webapps/charm/physician/routing/HealthPlan.jsp",
			"webapps/charm/physician/routing/HealthPlanDetails.jsp",
			"webapps/charm/physician/routing/MedicationsList.jsp", "webapps/charm/physician/routing/MedicationsTab.jsp",
			"webapps/charm/physician/routing/PaperRx.jsp", "webapps/charm/physician/routing/PaperRxIndia.jsp",
			"webapps/charm/physician/routing/PaperRxNonUS.jsp",
			"webapps/charm/physician/settings/labs/LabIntegration.jsp",
			"webapps/charm/physician/settings/labs/LabIntegrationPopup.jsp",
			"webapps/charm/physician/settings/plugins.jsp", "webapps/charm/physician/settings/pluginsSettings.jsp" };

	public static final String TAG_LIB_INCLUDE = "<%@ taglib prefix = \"enc\" uri = \"/WEB-INF/CharmEncoder.tld\"%>";
	public static final String IAM_JAR_INCLUDE = "<%@page import=\"com.adventnet.iam.xss.IAMEncoder\"%>";
	public static final String DELIMITER = "~";
	public static final String IGNORED_FILES = "Ignored_Files.txt";
	public static final String DATE_FORMAT = "dd-MM-yy-HH-mm-ss";
}
