//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flexCacheRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flexCacheRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="StartAccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;/choice>
 *         &lt;element name="BatchFailedAcctNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FlexRequestedAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlexRedeemedAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FlexHostTrace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlexAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlexAcctBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlexAcctPriorBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlexAcctExpireDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefIdx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApprovalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuthCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CVV2RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AutoAuthTxRefIdx" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthTxRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthProcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthStatusMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthApprovalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthFlexRedeemedAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthAuthCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthRespCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthFlexHostTrace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthFlexAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AutoAuthRespTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FraudScoreProcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudScoreProcMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudAnalysisResponse" type="{}fraudAnalysisRespType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flexCacheRespType", propOrder = {
    "merchantID",
    "terminalID",
    "orderID",
    "accountNum",
    "startAccountNum",
    "batchFailedAcctNum",
    "flexRequestedAmount",
    "flexRedeemedAmt",
    "flexHostTrace",
    "flexAction",
    "flexAcctBalance",
    "flexAcctPriorBalance",
    "flexAcctExpireDate",
    "cardBrand",
    "txRefNum",
    "txRefIdx",
    "procStatus",
    "statusMsg",
    "approvalStatus",
    "authCode",
    "respCode",
    "cvv2RespCode",
    "autoAuthTxRefIdx",
    "autoAuthTxRefNum",
    "autoAuthProcStatus",
    "autoAuthStatusMsg",
    "autoAuthApprovalStatus",
    "autoAuthFlexRedeemedAmt",
    "autoAuthAuthCode",
    "autoAuthRespCode",
    "autoAuthFlexHostTrace",
    "autoAuthFlexAction",
    "autoAuthRespTime",
    "respTime",
    "fraudScoreProcStatus",
    "fraudScoreProcMsg",
    "fraudAnalysisResponse"
})
public class FlexCacheRespType {

    @XmlElement(name = "MerchantID", required = true)
    protected String merchantID;
    @XmlElement(name = "TerminalID", required = true)
    protected String terminalID;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "AccountNum")
    protected String accountNum;
    @XmlElement(name = "StartAccountNum")
    protected String startAccountNum;
    @XmlElement(name = "BatchFailedAcctNum")
    protected String batchFailedAcctNum;
    @XmlElement(name = "FlexRequestedAmount", required = true)
    protected String flexRequestedAmount;
    @XmlElement(name = "FlexRedeemedAmt")
    protected String flexRedeemedAmt;
    @XmlElement(name = "FlexHostTrace", required = true)
    protected String flexHostTrace;
    @XmlElement(name = "FlexAction", required = true)
    protected String flexAction;
    @XmlElement(name = "FlexAcctBalance", required = true)
    protected String flexAcctBalance;
    @XmlElement(name = "FlexAcctPriorBalance", required = true)
    protected String flexAcctPriorBalance;
    @XmlElement(name = "FlexAcctExpireDate")
    protected String flexAcctExpireDate;
    @XmlElement(name = "CardBrand", required = true)
    protected String cardBrand;
    @XmlElement(name = "TxRefNum", required = true)
    protected String txRefNum;
    @XmlElement(name = "TxRefIdx", required = true)
    protected String txRefIdx;
    @XmlElement(name = "ProcStatus", required = true)
    protected String procStatus;
    @XmlElement(name = "StatusMsg", required = true)
    protected String statusMsg;
    @XmlElement(name = "ApprovalStatus", required = true)
    protected String approvalStatus;
    @XmlElement(name = "AuthCode")
    protected String authCode;
    @XmlElement(name = "RespCode", required = true)
    protected String respCode;
    @XmlElement(name = "CVV2RespCode", required = true)
    protected String cvv2RespCode;
    @XmlElement(name = "AutoAuthTxRefIdx")
    protected String autoAuthTxRefIdx;
    @XmlElement(name = "AutoAuthTxRefNum")
    protected String autoAuthTxRefNum;
    @XmlElement(name = "AutoAuthProcStatus")
    protected String autoAuthProcStatus;
    @XmlElement(name = "AutoAuthStatusMsg")
    protected String autoAuthStatusMsg;
    @XmlElement(name = "AutoAuthApprovalStatus")
    protected String autoAuthApprovalStatus;
    @XmlElement(name = "AutoAuthFlexRedeemedAmt")
    protected String autoAuthFlexRedeemedAmt;
    @XmlElement(name = "AutoAuthAuthCode")
    protected String autoAuthAuthCode;
    @XmlElement(name = "AutoAuthRespCode")
    protected String autoAuthRespCode;
    @XmlElement(name = "AutoAuthFlexHostTrace")
    protected String autoAuthFlexHostTrace;
    @XmlElement(name = "AutoAuthFlexAction")
    protected String autoAuthFlexAction;
    @XmlElement(name = "AutoAuthRespTime")
    protected String autoAuthRespTime;
    @XmlElement(name = "RespTime", required = true)
    protected String respTime;
    @XmlElement(name = "FraudScoreProcStatus")
    protected String fraudScoreProcStatus;
    @XmlElement(name = "FraudScoreProcMsg")
    protected String fraudScoreProcMsg;
    @XmlElement(name = "FraudAnalysisResponse")
    protected FraudAnalysisRespType fraudAnalysisResponse;

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the startAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAccountNum() {
        return startAccountNum;
    }

    /**
     * Sets the value of the startAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAccountNum(String value) {
        this.startAccountNum = value;
    }

    /**
     * Gets the value of the batchFailedAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchFailedAcctNum() {
        return batchFailedAcctNum;
    }

    /**
     * Sets the value of the batchFailedAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchFailedAcctNum(String value) {
        this.batchFailedAcctNum = value;
    }

    /**
     * Gets the value of the flexRequestedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexRequestedAmount() {
        return flexRequestedAmount;
    }

    /**
     * Sets the value of the flexRequestedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexRequestedAmount(String value) {
        this.flexRequestedAmount = value;
    }

    /**
     * Gets the value of the flexRedeemedAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexRedeemedAmt() {
        return flexRedeemedAmt;
    }

    /**
     * Sets the value of the flexRedeemedAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexRedeemedAmt(String value) {
        this.flexRedeemedAmt = value;
    }

    /**
     * Gets the value of the flexHostTrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexHostTrace() {
        return flexHostTrace;
    }

    /**
     * Sets the value of the flexHostTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexHostTrace(String value) {
        this.flexHostTrace = value;
    }

    /**
     * Gets the value of the flexAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexAction() {
        return flexAction;
    }

    /**
     * Sets the value of the flexAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexAction(String value) {
        this.flexAction = value;
    }

    /**
     * Gets the value of the flexAcctBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexAcctBalance() {
        return flexAcctBalance;
    }

    /**
     * Sets the value of the flexAcctBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexAcctBalance(String value) {
        this.flexAcctBalance = value;
    }

    /**
     * Gets the value of the flexAcctPriorBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexAcctPriorBalance() {
        return flexAcctPriorBalance;
    }

    /**
     * Sets the value of the flexAcctPriorBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexAcctPriorBalance(String value) {
        this.flexAcctPriorBalance = value;
    }

    /**
     * Gets the value of the flexAcctExpireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexAcctExpireDate() {
        return flexAcctExpireDate;
    }

    /**
     * Sets the value of the flexAcctExpireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexAcctExpireDate(String value) {
        this.flexAcctExpireDate = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the txRefIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefIdx() {
        return txRefIdx;
    }

    /**
     * Sets the value of the txRefIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefIdx(String value) {
        this.txRefIdx = value;
    }

    /**
     * Gets the value of the procStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * Sets the value of the procStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcStatus(String value) {
        this.procStatus = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMsg(String value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the approvalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * Sets the value of the approvalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalStatus(String value) {
        this.approvalStatus = value;
    }

    /**
     * Gets the value of the authCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the cvv2RespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVV2RespCode() {
        return cvv2RespCode;
    }

    /**
     * Sets the value of the cvv2RespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVV2RespCode(String value) {
        this.cvv2RespCode = value;
    }

    /**
     * Gets the value of the autoAuthTxRefIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthTxRefIdx() {
        return autoAuthTxRefIdx;
    }

    /**
     * Sets the value of the autoAuthTxRefIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthTxRefIdx(String value) {
        this.autoAuthTxRefIdx = value;
    }

    /**
     * Gets the value of the autoAuthTxRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthTxRefNum() {
        return autoAuthTxRefNum;
    }

    /**
     * Sets the value of the autoAuthTxRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthTxRefNum(String value) {
        this.autoAuthTxRefNum = value;
    }

    /**
     * Gets the value of the autoAuthProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthProcStatus() {
        return autoAuthProcStatus;
    }

    /**
     * Sets the value of the autoAuthProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthProcStatus(String value) {
        this.autoAuthProcStatus = value;
    }

    /**
     * Gets the value of the autoAuthStatusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthStatusMsg() {
        return autoAuthStatusMsg;
    }

    /**
     * Sets the value of the autoAuthStatusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthStatusMsg(String value) {
        this.autoAuthStatusMsg = value;
    }

    /**
     * Gets the value of the autoAuthApprovalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthApprovalStatus() {
        return autoAuthApprovalStatus;
    }

    /**
     * Sets the value of the autoAuthApprovalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthApprovalStatus(String value) {
        this.autoAuthApprovalStatus = value;
    }

    /**
     * Gets the value of the autoAuthFlexRedeemedAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthFlexRedeemedAmt() {
        return autoAuthFlexRedeemedAmt;
    }

    /**
     * Sets the value of the autoAuthFlexRedeemedAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthFlexRedeemedAmt(String value) {
        this.autoAuthFlexRedeemedAmt = value;
    }

    /**
     * Gets the value of the autoAuthAuthCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthAuthCode() {
        return autoAuthAuthCode;
    }

    /**
     * Sets the value of the autoAuthAuthCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthAuthCode(String value) {
        this.autoAuthAuthCode = value;
    }

    /**
     * Gets the value of the autoAuthRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthRespCode() {
        return autoAuthRespCode;
    }

    /**
     * Sets the value of the autoAuthRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthRespCode(String value) {
        this.autoAuthRespCode = value;
    }

    /**
     * Gets the value of the autoAuthFlexHostTrace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthFlexHostTrace() {
        return autoAuthFlexHostTrace;
    }

    /**
     * Sets the value of the autoAuthFlexHostTrace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthFlexHostTrace(String value) {
        this.autoAuthFlexHostTrace = value;
    }

    /**
     * Gets the value of the autoAuthFlexAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthFlexAction() {
        return autoAuthFlexAction;
    }

    /**
     * Sets the value of the autoAuthFlexAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthFlexAction(String value) {
        this.autoAuthFlexAction = value;
    }

    /**
     * Gets the value of the autoAuthRespTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoAuthRespTime() {
        return autoAuthRespTime;
    }

    /**
     * Sets the value of the autoAuthRespTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoAuthRespTime(String value) {
        this.autoAuthRespTime = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

    /**
     * Gets the value of the fraudScoreProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudScoreProcStatus() {
        return fraudScoreProcStatus;
    }

    /**
     * Sets the value of the fraudScoreProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudScoreProcStatus(String value) {
        this.fraudScoreProcStatus = value;
    }

    /**
     * Gets the value of the fraudScoreProcMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudScoreProcMsg() {
        return fraudScoreProcMsg;
    }

    /**
     * Sets the value of the fraudScoreProcMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudScoreProcMsg(String value) {
        this.fraudScoreProcMsg = value;
    }

    /**
     * Gets the value of the fraudAnalysisResponse property.
     * 
     * @return
     *     possible object is
     *     {@link FraudAnalysisRespType }
     *     
     */
    public FraudAnalysisRespType getFraudAnalysisResponse() {
        return fraudAnalysisResponse;
    }

    /**
     * Sets the value of the fraudAnalysisResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudAnalysisRespType }
     *     
     */
    public void setFraudAnalysisResponse(FraudAnalysisRespType value) {
        this.fraudAnalysisResponse = value;
    }

}
