//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fraudAnalysisRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fraudAnalysisRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FraudScoreIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FraudStatusCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RiskInquiryTransactionID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AutoDecisionResponse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RiskScore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="KaptchaMatchFlag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WorstCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PaymentBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FourteenDayVelocity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SixHourVelocity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerNetwork" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfDevices" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfCards" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NumberOfEmails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceLayers" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceFingerprint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerTimeZone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerLocalDateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceRegion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeviceCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProxyStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JavascriptStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FlashStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CookiesStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrowserCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BrowserLanguage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MobileDeviceIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MobileDeviceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MobileWirelessIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="VoiceDevice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PCRemoteIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RulesDataLength" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RulesData" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fraudAnalysisRespType", propOrder = {
    "fraudScoreIndicator",
    "fraudStatusCode",
    "riskInquiryTransactionID",
    "autoDecisionResponse",
    "riskScore",
    "kaptchaMatchFlag",
    "worstCountry",
    "customerRegion",
    "paymentBrand",
    "fourteenDayVelocity",
    "sixHourVelocity",
    "customerNetwork",
    "numberOfDevices",
    "numberOfCards",
    "numberOfEmails",
    "deviceLayers",
    "deviceFingerprint",
    "customerTimeZone",
    "customerLocalDateTime",
    "deviceRegion",
    "deviceCountry",
    "proxyStatus",
    "javascriptStatus",
    "flashStatus",
    "cookiesStatus",
    "browserCountry",
    "browserLanguage",
    "mobileDeviceIndicator",
    "mobileDeviceType",
    "mobileWirelessIndicator",
    "voiceDevice",
    "pcRemoteIndicator",
    "rulesDataLength",
    "rulesData"
})
public class FraudAnalysisRespType {

    @XmlElement(name = "FraudScoreIndicator", required = true)
    protected String fraudScoreIndicator;
    @XmlElement(name = "FraudStatusCode", required = true)
    protected String fraudStatusCode;
    @XmlElement(name = "RiskInquiryTransactionID", required = true)
    protected String riskInquiryTransactionID;
    @XmlElement(name = "AutoDecisionResponse", required = true)
    protected String autoDecisionResponse;
    @XmlElement(name = "RiskScore", required = true)
    protected String riskScore;
    @XmlElement(name = "KaptchaMatchFlag", required = true)
    protected String kaptchaMatchFlag;
    @XmlElement(name = "WorstCountry", required = true)
    protected String worstCountry;
    @XmlElement(name = "CustomerRegion", required = true)
    protected String customerRegion;
    @XmlElement(name = "PaymentBrand", required = true)
    protected String paymentBrand;
    @XmlElement(name = "FourteenDayVelocity", required = true)
    protected String fourteenDayVelocity;
    @XmlElement(name = "SixHourVelocity", required = true)
    protected String sixHourVelocity;
    @XmlElement(name = "CustomerNetwork", required = true)
    protected String customerNetwork;
    @XmlElement(name = "NumberOfDevices", required = true)
    protected String numberOfDevices;
    @XmlElement(name = "NumberOfCards", required = true)
    protected String numberOfCards;
    @XmlElement(name = "NumberOfEmails", required = true)
    protected String numberOfEmails;
    @XmlElement(name = "DeviceLayers", required = true)
    protected String deviceLayers;
    @XmlElement(name = "DeviceFingerprint", required = true)
    protected String deviceFingerprint;
    @XmlElement(name = "CustomerTimeZone", required = true)
    protected String customerTimeZone;
    @XmlElement(name = "CustomerLocalDateTime", required = true)
    protected String customerLocalDateTime;
    @XmlElement(name = "DeviceRegion", required = true)
    protected String deviceRegion;
    @XmlElement(name = "DeviceCountry", required = true)
    protected String deviceCountry;
    @XmlElement(name = "ProxyStatus", required = true)
    protected String proxyStatus;
    @XmlElement(name = "JavascriptStatus", required = true)
    protected String javascriptStatus;
    @XmlElement(name = "FlashStatus", required = true)
    protected String flashStatus;
    @XmlElement(name = "CookiesStatus", required = true)
    protected String cookiesStatus;
    @XmlElement(name = "BrowserCountry", required = true)
    protected String browserCountry;
    @XmlElement(name = "BrowserLanguage", required = true)
    protected String browserLanguage;
    @XmlElement(name = "MobileDeviceIndicator", required = true)
    protected String mobileDeviceIndicator;
    @XmlElement(name = "MobileDeviceType", required = true)
    protected String mobileDeviceType;
    @XmlElement(name = "MobileWirelessIndicator", required = true)
    protected String mobileWirelessIndicator;
    @XmlElement(name = "VoiceDevice", required = true)
    protected String voiceDevice;
    @XmlElement(name = "PCRemoteIndicator", required = true)
    protected String pcRemoteIndicator;
    @XmlElement(name = "RulesDataLength", required = true)
    protected String rulesDataLength;
    @XmlElement(name = "RulesData", required = true)
    protected String rulesData;

    /**
     * Gets the value of the fraudScoreIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudScoreIndicator() {
        return fraudScoreIndicator;
    }

    /**
     * Sets the value of the fraudScoreIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudScoreIndicator(String value) {
        this.fraudScoreIndicator = value;
    }

    /**
     * Gets the value of the fraudStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudStatusCode() {
        return fraudStatusCode;
    }

    /**
     * Sets the value of the fraudStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudStatusCode(String value) {
        this.fraudStatusCode = value;
    }

    /**
     * Gets the value of the riskInquiryTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskInquiryTransactionID() {
        return riskInquiryTransactionID;
    }

    /**
     * Sets the value of the riskInquiryTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskInquiryTransactionID(String value) {
        this.riskInquiryTransactionID = value;
    }

    /**
     * Gets the value of the autoDecisionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoDecisionResponse() {
        return autoDecisionResponse;
    }

    /**
     * Sets the value of the autoDecisionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoDecisionResponse(String value) {
        this.autoDecisionResponse = value;
    }

    /**
     * Gets the value of the riskScore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRiskScore() {
        return riskScore;
    }

    /**
     * Sets the value of the riskScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRiskScore(String value) {
        this.riskScore = value;
    }

    /**
     * Gets the value of the kaptchaMatchFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKaptchaMatchFlag() {
        return kaptchaMatchFlag;
    }

    /**
     * Sets the value of the kaptchaMatchFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKaptchaMatchFlag(String value) {
        this.kaptchaMatchFlag = value;
    }

    /**
     * Gets the value of the worstCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorstCountry() {
        return worstCountry;
    }

    /**
     * Sets the value of the worstCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorstCountry(String value) {
        this.worstCountry = value;
    }

    /**
     * Gets the value of the customerRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRegion() {
        return customerRegion;
    }

    /**
     * Sets the value of the customerRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRegion(String value) {
        this.customerRegion = value;
    }

    /**
     * Gets the value of the paymentBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentBrand() {
        return paymentBrand;
    }

    /**
     * Sets the value of the paymentBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentBrand(String value) {
        this.paymentBrand = value;
    }

    /**
     * Gets the value of the fourteenDayVelocity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFourteenDayVelocity() {
        return fourteenDayVelocity;
    }

    /**
     * Sets the value of the fourteenDayVelocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFourteenDayVelocity(String value) {
        this.fourteenDayVelocity = value;
    }

    /**
     * Gets the value of the sixHourVelocity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSixHourVelocity() {
        return sixHourVelocity;
    }

    /**
     * Sets the value of the sixHourVelocity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSixHourVelocity(String value) {
        this.sixHourVelocity = value;
    }

    /**
     * Gets the value of the customerNetwork property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerNetwork() {
        return customerNetwork;
    }

    /**
     * Sets the value of the customerNetwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerNetwork(String value) {
        this.customerNetwork = value;
    }

    /**
     * Gets the value of the numberOfDevices property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfDevices() {
        return numberOfDevices;
    }

    /**
     * Sets the value of the numberOfDevices property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfDevices(String value) {
        this.numberOfDevices = value;
    }

    /**
     * Gets the value of the numberOfCards property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfCards() {
        return numberOfCards;
    }

    /**
     * Sets the value of the numberOfCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfCards(String value) {
        this.numberOfCards = value;
    }

    /**
     * Gets the value of the numberOfEmails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfEmails() {
        return numberOfEmails;
    }

    /**
     * Sets the value of the numberOfEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfEmails(String value) {
        this.numberOfEmails = value;
    }

    /**
     * Gets the value of the deviceLayers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceLayers() {
        return deviceLayers;
    }

    /**
     * Sets the value of the deviceLayers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceLayers(String value) {
        this.deviceLayers = value;
    }

    /**
     * Gets the value of the deviceFingerprint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceFingerprint() {
        return deviceFingerprint;
    }

    /**
     * Sets the value of the deviceFingerprint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceFingerprint(String value) {
        this.deviceFingerprint = value;
    }

    /**
     * Gets the value of the customerTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerTimeZone() {
        return customerTimeZone;
    }

    /**
     * Sets the value of the customerTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerTimeZone(String value) {
        this.customerTimeZone = value;
    }

    /**
     * Gets the value of the customerLocalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerLocalDateTime() {
        return customerLocalDateTime;
    }

    /**
     * Sets the value of the customerLocalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerLocalDateTime(String value) {
        this.customerLocalDateTime = value;
    }

    /**
     * Gets the value of the deviceRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceRegion() {
        return deviceRegion;
    }

    /**
     * Sets the value of the deviceRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceRegion(String value) {
        this.deviceRegion = value;
    }

    /**
     * Gets the value of the deviceCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceCountry() {
        return deviceCountry;
    }

    /**
     * Sets the value of the deviceCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceCountry(String value) {
        this.deviceCountry = value;
    }

    /**
     * Gets the value of the proxyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProxyStatus() {
        return proxyStatus;
    }

    /**
     * Sets the value of the proxyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProxyStatus(String value) {
        this.proxyStatus = value;
    }

    /**
     * Gets the value of the javascriptStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavascriptStatus() {
        return javascriptStatus;
    }

    /**
     * Sets the value of the javascriptStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavascriptStatus(String value) {
        this.javascriptStatus = value;
    }

    /**
     * Gets the value of the flashStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlashStatus() {
        return flashStatus;
    }

    /**
     * Sets the value of the flashStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlashStatus(String value) {
        this.flashStatus = value;
    }

    /**
     * Gets the value of the cookiesStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCookiesStatus() {
        return cookiesStatus;
    }

    /**
     * Sets the value of the cookiesStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCookiesStatus(String value) {
        this.cookiesStatus = value;
    }

    /**
     * Gets the value of the browserCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowserCountry() {
        return browserCountry;
    }

    /**
     * Sets the value of the browserCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowserCountry(String value) {
        this.browserCountry = value;
    }

    /**
     * Gets the value of the browserLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrowserLanguage() {
        return browserLanguage;
    }

    /**
     * Sets the value of the browserLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrowserLanguage(String value) {
        this.browserLanguage = value;
    }

    /**
     * Gets the value of the mobileDeviceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileDeviceIndicator() {
        return mobileDeviceIndicator;
    }

    /**
     * Sets the value of the mobileDeviceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileDeviceIndicator(String value) {
        this.mobileDeviceIndicator = value;
    }

    /**
     * Gets the value of the mobileDeviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileDeviceType() {
        return mobileDeviceType;
    }

    /**
     * Sets the value of the mobileDeviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileDeviceType(String value) {
        this.mobileDeviceType = value;
    }

    /**
     * Gets the value of the mobileWirelessIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobileWirelessIndicator() {
        return mobileWirelessIndicator;
    }

    /**
     * Sets the value of the mobileWirelessIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobileWirelessIndicator(String value) {
        this.mobileWirelessIndicator = value;
    }

    /**
     * Gets the value of the voiceDevice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoiceDevice() {
        return voiceDevice;
    }

    /**
     * Sets the value of the voiceDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoiceDevice(String value) {
        this.voiceDevice = value;
    }

    /**
     * Gets the value of the pcRemoteIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCRemoteIndicator() {
        return pcRemoteIndicator;
    }

    /**
     * Sets the value of the pcRemoteIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCRemoteIndicator(String value) {
        this.pcRemoteIndicator = value;
    }

    /**
     * Gets the value of the rulesDataLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRulesDataLength() {
        return rulesDataLength;
    }

    /**
     * Sets the value of the rulesDataLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRulesDataLength(String value) {
        this.rulesDataLength = value;
    }

    /**
     * Gets the value of the rulesData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRulesData() {
        return rulesData;
    }

    /**
     * Sets the value of the rulesData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRulesData(String value) {
        this.rulesData = value;
    }

}
