//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for inquiryRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inquiryRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndustryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefIdx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApprovalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AVSRespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CVV2RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AuthCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RecurringAdviceCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CAVVRespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HostRespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HostAVSRespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HostCVV2RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProfileProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerProfileMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BillerReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentDaysLeft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentDollarsLeft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PartialAuthOccurred" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RequestedAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RedeemedAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemainingBalance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CountryFraudFilterStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IsoCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FraudScoreProcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudScoreProcMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudAnalysisResponse" type="{}fraudAnalysisRespType" minOccurs="0"/>
 *         &lt;element name="CTIAffluentCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTICommercialCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTIDurbinExemption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTIHealthcareCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTILevel3Eligible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTIPayrollCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTIPrepaidCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTIPINlessDebitCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTISignatureDebitCard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CTIIssuingCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankSortCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDRibCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDMandateSignatureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDMandateID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDMandateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TokenAssuranceLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DPANAccountStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inquiryRespType", propOrder = {
    "industryType",
    "messageType",
    "merchantID",
    "terminalID",
    "cardBrand",
    "accountNum",
    "orderID",
    "txRefNum",
    "txRefIdx",
    "procStatus",
    "approvalStatus",
    "respCode",
    "avsRespCode",
    "cvv2RespCode",
    "authCode",
    "recurringAdviceCd",
    "cavvRespCode",
    "statusMsg",
    "respMsg",
    "hostRespCode",
    "hostAVSRespCode",
    "hostCVV2RespCode",
    "customerRefNum",
    "customerName",
    "profileProcStatus",
    "customerProfileMessage",
    "billerReferenceNumber",
    "mbStatus",
    "mbMicroPaymentDaysLeft",
    "mbMicroPaymentDollarsLeft",
    "respTime",
    "partialAuthOccurred",
    "requestedAmount",
    "redeemedAmount",
    "remainingBalance",
    "countryFraudFilterStatus",
    "isoCountryCode",
    "fraudScoreProcStatus",
    "fraudScoreProcMsg",
    "fraudAnalysisResponse",
    "ctiAffluentCard",
    "ctiCommercialCard",
    "ctiDurbinExemption",
    "ctiHealthcareCard",
    "ctiLevel3Eligible",
    "ctiPayrollCard",
    "ctiPrepaidCard",
    "ctipiNlessDebitCard",
    "ctiSignatureDebitCard",
    "ctiIssuingCountry",
    "euddCountryCode",
    "euddBankSortCode",
    "euddRibCode",
    "euddBankBranchCode",
    "euddiban",
    "euddbic",
    "euddMandateSignatureDate",
    "euddMandateID",
    "euddMandateType",
    "tokenAssuranceLevel",
    "dpanAccountStatus"
})
public class InquiryRespType {

    @XmlElement(name = "IndustryType", required = true)
    protected String industryType;
    @XmlElement(name = "MessageType", required = true)
    protected String messageType;
    @XmlElement(name = "MerchantID", required = true)
    protected String merchantID;
    @XmlElement(name = "TerminalID", required = true)
    protected String terminalID;
    @XmlElement(name = "CardBrand", required = true)
    protected String cardBrand;
    @XmlElement(name = "AccountNum", required = true)
    protected String accountNum;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "TxRefNum", required = true)
    protected String txRefNum;
    @XmlElement(name = "TxRefIdx", required = true)
    protected String txRefIdx;
    @XmlElement(name = "ProcStatus", required = true)
    protected String procStatus;
    @XmlElement(name = "ApprovalStatus", required = true)
    protected String approvalStatus;
    @XmlElement(name = "RespCode", required = true)
    protected String respCode;
    @XmlElement(name = "AVSRespCode", required = true)
    protected String avsRespCode;
    @XmlElement(name = "CVV2RespCode", required = true)
    protected String cvv2RespCode;
    @XmlElement(name = "AuthCode", required = true)
    protected String authCode;
    @XmlElement(name = "RecurringAdviceCd", required = true)
    protected String recurringAdviceCd;
    @XmlElement(name = "CAVVRespCode", required = true)
    protected String cavvRespCode;
    @XmlElement(name = "StatusMsg", required = true)
    protected String statusMsg;
    @XmlElement(name = "RespMsg", required = true)
    protected String respMsg;
    @XmlElement(name = "HostRespCode", required = true)
    protected String hostRespCode;
    @XmlElement(name = "HostAVSRespCode", required = true)
    protected String hostAVSRespCode;
    @XmlElement(name = "HostCVV2RespCode", required = true)
    protected String hostCVV2RespCode;
    @XmlElement(name = "CustomerRefNum", required = true)
    protected String customerRefNum;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "ProfileProcStatus", required = true)
    protected String profileProcStatus;
    @XmlElement(name = "CustomerProfileMessage", required = true)
    protected String customerProfileMessage;
    @XmlElement(name = "BillerReferenceNumber")
    protected String billerReferenceNumber;
    @XmlElement(name = "MBStatus")
    protected String mbStatus;
    @XmlElement(name = "MBMicroPaymentDaysLeft")
    protected String mbMicroPaymentDaysLeft;
    @XmlElement(name = "MBMicroPaymentDollarsLeft")
    protected String mbMicroPaymentDollarsLeft;
    @XmlElement(name = "RespTime", required = true)
    protected String respTime;
    @XmlElement(name = "PartialAuthOccurred", required = true)
    protected String partialAuthOccurred;
    @XmlElement(name = "RequestedAmount", required = true)
    protected String requestedAmount;
    @XmlElement(name = "RedeemedAmount", required = true)
    protected String redeemedAmount;
    @XmlElement(name = "RemainingBalance", required = true)
    protected String remainingBalance;
    @XmlElement(name = "CountryFraudFilterStatus", required = true)
    protected String countryFraudFilterStatus;
    @XmlElement(name = "IsoCountryCode", required = true)
    protected String isoCountryCode;
    @XmlElement(name = "FraudScoreProcStatus")
    protected String fraudScoreProcStatus;
    @XmlElement(name = "FraudScoreProcMsg")
    protected String fraudScoreProcMsg;
    @XmlElement(name = "FraudAnalysisResponse")
    protected FraudAnalysisRespType fraudAnalysisResponse;
    @XmlElement(name = "CTIAffluentCard")
    protected String ctiAffluentCard;
    @XmlElement(name = "CTICommercialCard")
    protected String ctiCommercialCard;
    @XmlElement(name = "CTIDurbinExemption")
    protected String ctiDurbinExemption;
    @XmlElement(name = "CTIHealthcareCard")
    protected String ctiHealthcareCard;
    @XmlElement(name = "CTILevel3Eligible")
    protected String ctiLevel3Eligible;
    @XmlElement(name = "CTIPayrollCard")
    protected String ctiPayrollCard;
    @XmlElement(name = "CTIPrepaidCard")
    protected String ctiPrepaidCard;
    @XmlElement(name = "CTIPINlessDebitCard")
    protected String ctipiNlessDebitCard;
    @XmlElement(name = "CTISignatureDebitCard")
    protected String ctiSignatureDebitCard;
    @XmlElement(name = "CTIIssuingCountry")
    protected String ctiIssuingCountry;
    @XmlElement(name = "EUDDCountryCode")
    protected String euddCountryCode;
    @XmlElement(name = "EUDDBankSortCode")
    protected String euddBankSortCode;
    @XmlElement(name = "EUDDRibCode")
    protected String euddRibCode;
    @XmlElement(name = "EUDDBankBranchCode")
    protected String euddBankBranchCode;
    @XmlElement(name = "EUDDIBAN")
    protected String euddiban;
    @XmlElement(name = "EUDDBIC")
    protected String euddbic;
    @XmlElement(name = "EUDDMandateSignatureDate")
    protected String euddMandateSignatureDate;
    @XmlElement(name = "EUDDMandateID")
    protected String euddMandateID;
    @XmlElement(name = "EUDDMandateType")
    protected String euddMandateType;
    @XmlElement(name = "TokenAssuranceLevel")
    protected String tokenAssuranceLevel;
    @XmlElement(name = "DPANAccountStatus")
    protected String dpanAccountStatus;

    /**
     * Gets the value of the industryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryType() {
        return industryType;
    }

    /**
     * Sets the value of the industryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryType(String value) {
        this.industryType = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the txRefIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefIdx() {
        return txRefIdx;
    }

    /**
     * Sets the value of the txRefIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefIdx(String value) {
        this.txRefIdx = value;
    }

    /**
     * Gets the value of the procStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * Sets the value of the procStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcStatus(String value) {
        this.procStatus = value;
    }

    /**
     * Gets the value of the approvalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * Sets the value of the approvalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalStatus(String value) {
        this.approvalStatus = value;
    }

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the avsRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSRespCode() {
        return avsRespCode;
    }

    /**
     * Sets the value of the avsRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSRespCode(String value) {
        this.avsRespCode = value;
    }

    /**
     * Gets the value of the cvv2RespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVV2RespCode() {
        return cvv2RespCode;
    }

    /**
     * Sets the value of the cvv2RespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVV2RespCode(String value) {
        this.cvv2RespCode = value;
    }

    /**
     * Gets the value of the authCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * Sets the value of the authCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthCode(String value) {
        this.authCode = value;
    }

    /**
     * Gets the value of the recurringAdviceCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecurringAdviceCd() {
        return recurringAdviceCd;
    }

    /**
     * Sets the value of the recurringAdviceCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecurringAdviceCd(String value) {
        this.recurringAdviceCd = value;
    }

    /**
     * Gets the value of the cavvRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAVVRespCode() {
        return cavvRespCode;
    }

    /**
     * Sets the value of the cavvRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAVVRespCode(String value) {
        this.cavvRespCode = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMsg(String value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the respMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * Sets the value of the respMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespMsg(String value) {
        this.respMsg = value;
    }

    /**
     * Gets the value of the hostRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostRespCode() {
        return hostRespCode;
    }

    /**
     * Sets the value of the hostRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostRespCode(String value) {
        this.hostRespCode = value;
    }

    /**
     * Gets the value of the hostAVSRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostAVSRespCode() {
        return hostAVSRespCode;
    }

    /**
     * Sets the value of the hostAVSRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostAVSRespCode(String value) {
        this.hostAVSRespCode = value;
    }

    /**
     * Gets the value of the hostCVV2RespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostCVV2RespCode() {
        return hostCVV2RespCode;
    }

    /**
     * Sets the value of the hostCVV2RespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostCVV2RespCode(String value) {
        this.hostCVV2RespCode = value;
    }

    /**
     * Gets the value of the customerRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRefNum() {
        return customerRefNum;
    }

    /**
     * Sets the value of the customerRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRefNum(String value) {
        this.customerRefNum = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the profileProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileProcStatus() {
        return profileProcStatus;
    }

    /**
     * Sets the value of the profileProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileProcStatus(String value) {
        this.profileProcStatus = value;
    }

    /**
     * Gets the value of the customerProfileMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileMessage() {
        return customerProfileMessage;
    }

    /**
     * Sets the value of the customerProfileMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileMessage(String value) {
        this.customerProfileMessage = value;
    }

    /**
     * Gets the value of the billerReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerReferenceNumber() {
        return billerReferenceNumber;
    }

    /**
     * Sets the value of the billerReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerReferenceNumber(String value) {
        this.billerReferenceNumber = value;
    }

    /**
     * Gets the value of the mbStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBStatus() {
        return mbStatus;
    }

    /**
     * Sets the value of the mbStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBStatus(String value) {
        this.mbStatus = value;
    }

    /**
     * Gets the value of the mbMicroPaymentDaysLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentDaysLeft() {
        return mbMicroPaymentDaysLeft;
    }

    /**
     * Sets the value of the mbMicroPaymentDaysLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentDaysLeft(String value) {
        this.mbMicroPaymentDaysLeft = value;
    }

    /**
     * Gets the value of the mbMicroPaymentDollarsLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentDollarsLeft() {
        return mbMicroPaymentDollarsLeft;
    }

    /**
     * Sets the value of the mbMicroPaymentDollarsLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentDollarsLeft(String value) {
        this.mbMicroPaymentDollarsLeft = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

    /**
     * Gets the value of the partialAuthOccurred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialAuthOccurred() {
        return partialAuthOccurred;
    }

    /**
     * Sets the value of the partialAuthOccurred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialAuthOccurred(String value) {
        this.partialAuthOccurred = value;
    }

    /**
     * Gets the value of the requestedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedAmount() {
        return requestedAmount;
    }

    /**
     * Sets the value of the requestedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedAmount(String value) {
        this.requestedAmount = value;
    }

    /**
     * Gets the value of the redeemedAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedeemedAmount() {
        return redeemedAmount;
    }

    /**
     * Sets the value of the redeemedAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedeemedAmount(String value) {
        this.redeemedAmount = value;
    }

    /**
     * Gets the value of the remainingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingBalance() {
        return remainingBalance;
    }

    /**
     * Sets the value of the remainingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingBalance(String value) {
        this.remainingBalance = value;
    }

    /**
     * Gets the value of the countryFraudFilterStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryFraudFilterStatus() {
        return countryFraudFilterStatus;
    }

    /**
     * Sets the value of the countryFraudFilterStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryFraudFilterStatus(String value) {
        this.countryFraudFilterStatus = value;
    }

    /**
     * Gets the value of the isoCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsoCountryCode() {
        return isoCountryCode;
    }

    /**
     * Sets the value of the isoCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsoCountryCode(String value) {
        this.isoCountryCode = value;
    }

    /**
     * Gets the value of the fraudScoreProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudScoreProcStatus() {
        return fraudScoreProcStatus;
    }

    /**
     * Sets the value of the fraudScoreProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudScoreProcStatus(String value) {
        this.fraudScoreProcStatus = value;
    }

    /**
     * Gets the value of the fraudScoreProcMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudScoreProcMsg() {
        return fraudScoreProcMsg;
    }

    /**
     * Sets the value of the fraudScoreProcMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudScoreProcMsg(String value) {
        this.fraudScoreProcMsg = value;
    }

    /**
     * Gets the value of the fraudAnalysisResponse property.
     * 
     * @return
     *     possible object is
     *     {@link FraudAnalysisRespType }
     *     
     */
    public FraudAnalysisRespType getFraudAnalysisResponse() {
        return fraudAnalysisResponse;
    }

    /**
     * Sets the value of the fraudAnalysisResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudAnalysisRespType }
     *     
     */
    public void setFraudAnalysisResponse(FraudAnalysisRespType value) {
        this.fraudAnalysisResponse = value;
    }

    /**
     * Gets the value of the ctiAffluentCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIAffluentCard() {
        return ctiAffluentCard;
    }

    /**
     * Sets the value of the ctiAffluentCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIAffluentCard(String value) {
        this.ctiAffluentCard = value;
    }

    /**
     * Gets the value of the ctiCommercialCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTICommercialCard() {
        return ctiCommercialCard;
    }

    /**
     * Sets the value of the ctiCommercialCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTICommercialCard(String value) {
        this.ctiCommercialCard = value;
    }

    /**
     * Gets the value of the ctiDurbinExemption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIDurbinExemption() {
        return ctiDurbinExemption;
    }

    /**
     * Sets the value of the ctiDurbinExemption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIDurbinExemption(String value) {
        this.ctiDurbinExemption = value;
    }

    /**
     * Gets the value of the ctiHealthcareCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIHealthcareCard() {
        return ctiHealthcareCard;
    }

    /**
     * Sets the value of the ctiHealthcareCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIHealthcareCard(String value) {
        this.ctiHealthcareCard = value;
    }

    /**
     * Gets the value of the ctiLevel3Eligible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTILevel3Eligible() {
        return ctiLevel3Eligible;
    }

    /**
     * Sets the value of the ctiLevel3Eligible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTILevel3Eligible(String value) {
        this.ctiLevel3Eligible = value;
    }

    /**
     * Gets the value of the ctiPayrollCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIPayrollCard() {
        return ctiPayrollCard;
    }

    /**
     * Sets the value of the ctiPayrollCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIPayrollCard(String value) {
        this.ctiPayrollCard = value;
    }

    /**
     * Gets the value of the ctiPrepaidCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIPrepaidCard() {
        return ctiPrepaidCard;
    }

    /**
     * Sets the value of the ctiPrepaidCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIPrepaidCard(String value) {
        this.ctiPrepaidCard = value;
    }

    /**
     * Gets the value of the ctipiNlessDebitCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIPINlessDebitCard() {
        return ctipiNlessDebitCard;
    }

    /**
     * Sets the value of the ctipiNlessDebitCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIPINlessDebitCard(String value) {
        this.ctipiNlessDebitCard = value;
    }

    /**
     * Gets the value of the ctiSignatureDebitCard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTISignatureDebitCard() {
        return ctiSignatureDebitCard;
    }

    /**
     * Sets the value of the ctiSignatureDebitCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTISignatureDebitCard(String value) {
        this.ctiSignatureDebitCard = value;
    }

    /**
     * Gets the value of the ctiIssuingCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCTIIssuingCountry() {
        return ctiIssuingCountry;
    }

    /**
     * Sets the value of the ctiIssuingCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCTIIssuingCountry(String value) {
        this.ctiIssuingCountry = value;
    }

    /**
     * Gets the value of the euddCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDCountryCode() {
        return euddCountryCode;
    }

    /**
     * Sets the value of the euddCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDCountryCode(String value) {
        this.euddCountryCode = value;
    }

    /**
     * Gets the value of the euddBankSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankSortCode() {
        return euddBankSortCode;
    }

    /**
     * Sets the value of the euddBankSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankSortCode(String value) {
        this.euddBankSortCode = value;
    }

    /**
     * Gets the value of the euddRibCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDRibCode() {
        return euddRibCode;
    }

    /**
     * Sets the value of the euddRibCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDRibCode(String value) {
        this.euddRibCode = value;
    }

    /**
     * Gets the value of the euddBankBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankBranchCode() {
        return euddBankBranchCode;
    }

    /**
     * Sets the value of the euddBankBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankBranchCode(String value) {
        this.euddBankBranchCode = value;
    }

    /**
     * Gets the value of the euddiban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDIBAN() {
        return euddiban;
    }

    /**
     * Sets the value of the euddiban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDIBAN(String value) {
        this.euddiban = value;
    }

    /**
     * Gets the value of the euddbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBIC() {
        return euddbic;
    }

    /**
     * Sets the value of the euddbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBIC(String value) {
        this.euddbic = value;
    }

    /**
     * Gets the value of the euddMandateSignatureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDMandateSignatureDate() {
        return euddMandateSignatureDate;
    }

    /**
     * Sets the value of the euddMandateSignatureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDMandateSignatureDate(String value) {
        this.euddMandateSignatureDate = value;
    }

    /**
     * Gets the value of the euddMandateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDMandateID() {
        return euddMandateID;
    }

    /**
     * Sets the value of the euddMandateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDMandateID(String value) {
        this.euddMandateID = value;
    }

    /**
     * Gets the value of the euddMandateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDMandateType() {
        return euddMandateType;
    }

    /**
     * Sets the value of the euddMandateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDMandateType(String value) {
        this.euddMandateType = value;
    }

    /**
     * Gets the value of the tokenAssuranceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenAssuranceLevel() {
        return tokenAssuranceLevel;
    }

    /**
     * Sets the value of the tokenAssuranceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenAssuranceLevel(String value) {
        this.tokenAssuranceLevel = value;
    }

    /**
     * Gets the value of the dpanAccountStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDPANAccountStatus() {
        return dpanAccountStatus;
    }

    /**
     * Sets the value of the dpanAccountStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDPANAccountStatus(String value) {
        this.dpanAccountStatus = value;
    }

}
