//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.medicalmine.chase.bean.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.medicalmine.chase.bean.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link FlexCacheRespType }
     * 
     */
    public FlexCacheRespType createFlexCacheRespType() {
        return new FlexCacheRespType();
    }

    /**
     * Create an instance of {@link NewOrderRespType }
     * 
     */
    public NewOrderRespType createNewOrderRespType() {
        return new NewOrderRespType();
    }

    /**
     * Create an instance of {@link ProfileRespType }
     * 
     */
    public ProfileRespType createProfileRespType() {
        return new ProfileRespType();
    }

    /**
     * Create an instance of {@link EndOfDayRespType }
     * 
     */
    public EndOfDayRespType createEndOfDayRespType() {
        return new EndOfDayRespType();
    }

    /**
     * Create an instance of {@link ReversalRespType }
     * 
     */
    public ReversalRespType createReversalRespType() {
        return new ReversalRespType();
    }

    /**
     * Create an instance of {@link MarkForCaptureRespType }
     * 
     */
    public MarkForCaptureRespType createMarkForCaptureRespType() {
        return new MarkForCaptureRespType();
    }

    /**
     * Create an instance of {@link QuickRespType }
     * 
     */
    public QuickRespType createQuickRespType() {
        return new QuickRespType();
    }

    /**
     * Create an instance of {@link QuickRespTypeOld }
     * 
     */
    public QuickRespTypeOld createQuickRespTypeOld() {
        return new QuickRespTypeOld();
    }

    /**
     * Create an instance of {@link InquiryRespType }
     * 
     */
    public InquiryRespType createInquiryRespType() {
        return new InquiryRespType();
    }

    /**
     * Create an instance of {@link AccountUpdaterRespType }
     * 
     */
    public AccountUpdaterRespType createAccountUpdaterRespType() {
        return new AccountUpdaterRespType();
    }

    /**
     * Create an instance of {@link SafetechFraudAnalysisRespType }
     * 
     */
    public SafetechFraudAnalysisRespType createSafetechFraudAnalysisRespType() {
        return new SafetechFraudAnalysisRespType();
    }

    /**
     * Create an instance of {@link SettleRejectHoldingBin }
     * 
     */
    public SettleRejectHoldingBin createSettleRejectHoldingBin() {
        return new SettleRejectHoldingBin();
    }

    /**
     * Create an instance of {@link StatusMsg }
     * 
     */
    public StatusMsg createStatusMsg() {
        return new StatusMsg();
    }

    /**
     * Create an instance of {@link FraudAnalysisRespType }
     * 
     */
    public FraudAnalysisRespType createFraudAnalysisRespType() {
        return new FraudAnalysisRespType();
    }

}
