//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for profileRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profileRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerBin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerMerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerProfileAction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProfileProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerProfileMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerAddress1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerAddress2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerCity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerZIP" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerCountryCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerProfileOrderOverrideInd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderDefaultDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderDefaultAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerAccountType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CCAccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CCExpireDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ECPAccountDDA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ECPAccountType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ECPAccountRT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ECPBankPmtDlv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SwitchSoloStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SwitchSoloIssueNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerMBStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBOrderIdGenerationMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBRecurringStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBRecurringEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBRecurringNoEndDateFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBRecurringMaxBillings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBRecurringFrequency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBDeferredBillDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentMaxDollarValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentMaxBillingDays" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentMaxTransactions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBCustomerStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentDaysLeft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MBMicroPaymentDollarsLeft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankSortCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDRibCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SDMerchantName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SDProductDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SDMerchantCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SDMerchantPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SDMerchantURL" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SDMerchantEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillerReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountUpdaterEligibility" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDMandateSignatureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDMandateID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDMandateType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DPANInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TokenRequestorID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MITMsgType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MITSubmittedTransactionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PinlessDebitTxnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PinlessDebitMerchantUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SafetechToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profileRespType", propOrder = {
    "customerBin",
    "customerMerchantID",
    "customerName",
    "customerRefNum",
    "customerProfileAction",
    "profileProcStatus",
    "customerProfileMessage",
    "customerAddress1",
    "customerAddress2",
    "customerCity",
    "customerState",
    "customerZIP",
    "customerEmail",
    "customerPhone",
    "customerCountryCode",
    "customerProfileOrderOverrideInd",
    "orderDefaultDescription",
    "orderDefaultAmount",
    "customerAccountType",
    "status",
    "cardBrand",
    "ccAccountNum",
    "ccExpireDate",
    "ecpAccountDDA",
    "ecpAccountType",
    "ecpAccountRT",
    "ecpBankPmtDlv",
    "switchSoloStartDate",
    "switchSoloIssueNum",
    "customerMBStatus",
    "mbType",
    "mbOrderIdGenerationMethod",
    "mbRecurringStartDate",
    "mbRecurringEndDate",
    "mbRecurringNoEndDateFlag",
    "mbRecurringMaxBillings",
    "mbRecurringFrequency",
    "mbDeferredBillDate",
    "mbMicroPaymentMaxDollarValue",
    "mbMicroPaymentMaxBillingDays",
    "mbMicroPaymentMaxTransactions",
    "mbCustomerStatus",
    "mbMicroPaymentDaysLeft",
    "mbMicroPaymentDollarsLeft",
    "euddCountryCode",
    "euddBankSortCode",
    "euddRibCode",
    "sdMerchantName",
    "sdProductDescription",
    "sdMerchantCity",
    "sdMerchantPhone",
    "sdMerchantURL",
    "sdMerchantEmail",
    "billerReferenceNumber",
    "respTime",
    "accountUpdaterEligibility",
    "euddBankBranchCode",
    "euddiban",
    "euddbic",
    "euddMandateSignatureDate",
    "euddMandateID",
    "euddMandateType",
    "dpanInd",
    "tokenRequestorID",
    "mitMsgType",
    "mitSubmittedTransactionID",
    "pinlessDebitTxnType",
    "pinlessDebitMerchantUrl",
    "safetechToken"
})
public class ProfileRespType {

    @XmlElement(name = "CustomerBin", required = true)
    protected String customerBin;
    @XmlElement(name = "CustomerMerchantID", required = true)
    protected String customerMerchantID;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "CustomerRefNum", required = true)
    protected String customerRefNum;
    @XmlElement(name = "CustomerProfileAction", required = true)
    protected String customerProfileAction;
    @XmlElement(name = "ProfileProcStatus", required = true)
    protected String profileProcStatus;
    @XmlElement(name = "CustomerProfileMessage", required = true)
    protected String customerProfileMessage;
    @XmlElement(name = "CustomerAddress1", required = true)
    protected String customerAddress1;
    @XmlElement(name = "CustomerAddress2", required = true)
    protected String customerAddress2;
    @XmlElement(name = "CustomerCity", required = true)
    protected String customerCity;
    @XmlElement(name = "CustomerState", required = true)
    protected String customerState;
    @XmlElement(name = "CustomerZIP", required = true)
    protected String customerZIP;
    @XmlElement(name = "CustomerEmail", required = true)
    protected String customerEmail;
    @XmlElement(name = "CustomerPhone", required = true)
    protected String customerPhone;
    @XmlElement(name = "CustomerCountryCode", required = true)
    protected String customerCountryCode;
    @XmlElement(name = "CustomerProfileOrderOverrideInd", required = true)
    protected String customerProfileOrderOverrideInd;
    @XmlElement(name = "OrderDefaultDescription", required = true)
    protected String orderDefaultDescription;
    @XmlElement(name = "OrderDefaultAmount", required = true)
    protected String orderDefaultAmount;
    @XmlElement(name = "CustomerAccountType", required = true)
    protected String customerAccountType;
    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "CardBrand", required = true)
    protected String cardBrand;
    @XmlElement(name = "CCAccountNum", required = true)
    protected String ccAccountNum;
    @XmlElement(name = "CCExpireDate", required = true)
    protected String ccExpireDate;
    @XmlElement(name = "ECPAccountDDA", required = true)
    protected String ecpAccountDDA;
    @XmlElement(name = "ECPAccountType", required = true)
    protected String ecpAccountType;
    @XmlElement(name = "ECPAccountRT", required = true)
    protected String ecpAccountRT;
    @XmlElement(name = "ECPBankPmtDlv", required = true)
    protected String ecpBankPmtDlv;
    @XmlElement(name = "SwitchSoloStartDate", required = true)
    protected String switchSoloStartDate;
    @XmlElement(name = "SwitchSoloIssueNum", required = true)
    protected String switchSoloIssueNum;
    @XmlElement(name = "CustomerMBStatus")
    protected String customerMBStatus;
    @XmlElement(name = "MBType")
    protected String mbType;
    @XmlElement(name = "MBOrderIdGenerationMethod")
    protected String mbOrderIdGenerationMethod;
    @XmlElement(name = "MBRecurringStartDate")
    protected String mbRecurringStartDate;
    @XmlElement(name = "MBRecurringEndDate")
    protected String mbRecurringEndDate;
    @XmlElement(name = "MBRecurringNoEndDateFlag")
    protected String mbRecurringNoEndDateFlag;
    @XmlElement(name = "MBRecurringMaxBillings")
    protected String mbRecurringMaxBillings;
    @XmlElement(name = "MBRecurringFrequency")
    protected String mbRecurringFrequency;
    @XmlElement(name = "MBDeferredBillDate")
    protected String mbDeferredBillDate;
    @XmlElement(name = "MBMicroPaymentMaxDollarValue")
    protected String mbMicroPaymentMaxDollarValue;
    @XmlElement(name = "MBMicroPaymentMaxBillingDays")
    protected String mbMicroPaymentMaxBillingDays;
    @XmlElement(name = "MBMicroPaymentMaxTransactions")
    protected String mbMicroPaymentMaxTransactions;
    @XmlElement(name = "MBCustomerStatus")
    protected String mbCustomerStatus;
    @XmlElement(name = "MBMicroPaymentDaysLeft")
    protected String mbMicroPaymentDaysLeft;
    @XmlElement(name = "MBMicroPaymentDollarsLeft")
    protected String mbMicroPaymentDollarsLeft;
    @XmlElement(name = "EUDDCountryCode")
    protected String euddCountryCode;
    @XmlElement(name = "EUDDBankSortCode")
    protected String euddBankSortCode;
    @XmlElement(name = "EUDDRibCode")
    protected String euddRibCode;
    @XmlElement(name = "SDMerchantName")
    protected String sdMerchantName;
    @XmlElement(name = "SDProductDescription")
    protected String sdProductDescription;
    @XmlElement(name = "SDMerchantCity")
    protected String sdMerchantCity;
    @XmlElement(name = "SDMerchantPhone")
    protected String sdMerchantPhone;
    @XmlElement(name = "SDMerchantURL")
    protected String sdMerchantURL;
    @XmlElement(name = "SDMerchantEmail")
    protected String sdMerchantEmail;
    @XmlElement(name = "BillerReferenceNumber", required = true)
    protected String billerReferenceNumber;
    @XmlElement(name = "RespTime", required = true)
    protected String respTime;
    @XmlElement(name = "AccountUpdaterEligibility")
    protected String accountUpdaterEligibility;
    @XmlElement(name = "EUDDBankBranchCode")
    protected String euddBankBranchCode;
    @XmlElement(name = "EUDDIBAN")
    protected String euddiban;
    @XmlElement(name = "EUDDBIC")
    protected String euddbic;
    @XmlElement(name = "EUDDMandateSignatureDate")
    protected String euddMandateSignatureDate;
    @XmlElement(name = "EUDDMandateID")
    protected String euddMandateID;
    @XmlElement(name = "EUDDMandateType")
    protected String euddMandateType;
    @XmlElement(name = "DPANInd")
    protected String dpanInd;
    @XmlElement(name = "TokenRequestorID")
    protected String tokenRequestorID;
    @XmlElement(name = "MITMsgType")
    protected String mitMsgType;
    @XmlElement(name = "MITSubmittedTransactionID")
    protected String mitSubmittedTransactionID;
    @XmlElement(name = "PinlessDebitTxnType")
    protected String pinlessDebitTxnType;
    @XmlElement(name = "PinlessDebitMerchantUrl")
    protected String pinlessDebitMerchantUrl;
    @XmlElement(name = "SafetechToken")
    protected String safetechToken;

    /**
     * Gets the value of the customerBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerBin() {
        return customerBin;
    }

    /**
     * Sets the value of the customerBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerBin(String value) {
        this.customerBin = value;
    }

    /**
     * Gets the value of the customerMerchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMerchantID() {
        return customerMerchantID;
    }

    /**
     * Sets the value of the customerMerchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMerchantID(String value) {
        this.customerMerchantID = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRefNum() {
        return customerRefNum;
    }

    /**
     * Sets the value of the customerRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRefNum(String value) {
        this.customerRefNum = value;
    }

    /**
     * Gets the value of the customerProfileAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileAction() {
        return customerProfileAction;
    }

    /**
     * Sets the value of the customerProfileAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileAction(String value) {
        this.customerProfileAction = value;
    }

    /**
     * Gets the value of the profileProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileProcStatus() {
        return profileProcStatus;
    }

    /**
     * Sets the value of the profileProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileProcStatus(String value) {
        this.profileProcStatus = value;
    }

    /**
     * Gets the value of the customerProfileMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileMessage() {
        return customerProfileMessage;
    }

    /**
     * Sets the value of the customerProfileMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileMessage(String value) {
        this.customerProfileMessage = value;
    }

    /**
     * Gets the value of the customerAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress1() {
        return customerAddress1;
    }

    /**
     * Sets the value of the customerAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress1(String value) {
        this.customerAddress1 = value;
    }

    /**
     * Gets the value of the customerAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress2() {
        return customerAddress2;
    }

    /**
     * Sets the value of the customerAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress2(String value) {
        this.customerAddress2 = value;
    }

    /**
     * Gets the value of the customerCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCity() {
        return customerCity;
    }

    /**
     * Sets the value of the customerCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCity(String value) {
        this.customerCity = value;
    }

    /**
     * Gets the value of the customerState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerState() {
        return customerState;
    }

    /**
     * Sets the value of the customerState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerState(String value) {
        this.customerState = value;
    }

    /**
     * Gets the value of the customerZIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerZIP() {
        return customerZIP;
    }

    /**
     * Sets the value of the customerZIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerZIP(String value) {
        this.customerZIP = value;
    }

    /**
     * Gets the value of the customerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the value of the customerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmail(String value) {
        this.customerEmail = value;
    }

    /**
     * Gets the value of the customerPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * Sets the value of the customerPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPhone(String value) {
        this.customerPhone = value;
    }

    /**
     * Gets the value of the customerCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCountryCode() {
        return customerCountryCode;
    }

    /**
     * Sets the value of the customerCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCountryCode(String value) {
        this.customerCountryCode = value;
    }

    /**
     * Gets the value of the customerProfileOrderOverrideInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileOrderOverrideInd() {
        return customerProfileOrderOverrideInd;
    }

    /**
     * Sets the value of the customerProfileOrderOverrideInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileOrderOverrideInd(String value) {
        this.customerProfileOrderOverrideInd = value;
    }

    /**
     * Gets the value of the orderDefaultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDefaultDescription() {
        return orderDefaultDescription;
    }

    /**
     * Sets the value of the orderDefaultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDefaultDescription(String value) {
        this.orderDefaultDescription = value;
    }

    /**
     * Gets the value of the orderDefaultAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDefaultAmount() {
        return orderDefaultAmount;
    }

    /**
     * Sets the value of the orderDefaultAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDefaultAmount(String value) {
        this.orderDefaultAmount = value;
    }

    /**
     * Gets the value of the customerAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAccountType() {
        return customerAccountType;
    }

    /**
     * Sets the value of the customerAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAccountType(String value) {
        this.customerAccountType = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the ccAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCAccountNum() {
        return ccAccountNum;
    }

    /**
     * Sets the value of the ccAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCAccountNum(String value) {
        this.ccAccountNum = value;
    }

    /**
     * Gets the value of the ccExpireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCExpireDate() {
        return ccExpireDate;
    }

    /**
     * Sets the value of the ccExpireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCExpireDate(String value) {
        this.ccExpireDate = value;
    }

    /**
     * Gets the value of the ecpAccountDDA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAccountDDA() {
        return ecpAccountDDA;
    }

    /**
     * Sets the value of the ecpAccountDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAccountDDA(String value) {
        this.ecpAccountDDA = value;
    }

    /**
     * Gets the value of the ecpAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAccountType() {
        return ecpAccountType;
    }

    /**
     * Sets the value of the ecpAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAccountType(String value) {
        this.ecpAccountType = value;
    }

    /**
     * Gets the value of the ecpAccountRT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAccountRT() {
        return ecpAccountRT;
    }

    /**
     * Sets the value of the ecpAccountRT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAccountRT(String value) {
        this.ecpAccountRT = value;
    }

    /**
     * Gets the value of the ecpBankPmtDlv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPBankPmtDlv() {
        return ecpBankPmtDlv;
    }

    /**
     * Sets the value of the ecpBankPmtDlv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPBankPmtDlv(String value) {
        this.ecpBankPmtDlv = value;
    }

    /**
     * Gets the value of the switchSoloStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchSoloStartDate() {
        return switchSoloStartDate;
    }

    /**
     * Sets the value of the switchSoloStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchSoloStartDate(String value) {
        this.switchSoloStartDate = value;
    }

    /**
     * Gets the value of the switchSoloIssueNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchSoloIssueNum() {
        return switchSoloIssueNum;
    }

    /**
     * Sets the value of the switchSoloIssueNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchSoloIssueNum(String value) {
        this.switchSoloIssueNum = value;
    }

    /**
     * Gets the value of the customerMBStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMBStatus() {
        return customerMBStatus;
    }

    /**
     * Sets the value of the customerMBStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMBStatus(String value) {
        this.customerMBStatus = value;
    }

    /**
     * Gets the value of the mbType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBType() {
        return mbType;
    }

    /**
     * Sets the value of the mbType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBType(String value) {
        this.mbType = value;
    }

    /**
     * Gets the value of the mbOrderIdGenerationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBOrderIdGenerationMethod() {
        return mbOrderIdGenerationMethod;
    }

    /**
     * Sets the value of the mbOrderIdGenerationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBOrderIdGenerationMethod(String value) {
        this.mbOrderIdGenerationMethod = value;
    }

    /**
     * Gets the value of the mbRecurringStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRecurringStartDate() {
        return mbRecurringStartDate;
    }

    /**
     * Sets the value of the mbRecurringStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRecurringStartDate(String value) {
        this.mbRecurringStartDate = value;
    }

    /**
     * Gets the value of the mbRecurringEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRecurringEndDate() {
        return mbRecurringEndDate;
    }

    /**
     * Sets the value of the mbRecurringEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRecurringEndDate(String value) {
        this.mbRecurringEndDate = value;
    }

    /**
     * Gets the value of the mbRecurringNoEndDateFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRecurringNoEndDateFlag() {
        return mbRecurringNoEndDateFlag;
    }

    /**
     * Sets the value of the mbRecurringNoEndDateFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRecurringNoEndDateFlag(String value) {
        this.mbRecurringNoEndDateFlag = value;
    }

    /**
     * Gets the value of the mbRecurringMaxBillings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRecurringMaxBillings() {
        return mbRecurringMaxBillings;
    }

    /**
     * Sets the value of the mbRecurringMaxBillings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRecurringMaxBillings(String value) {
        this.mbRecurringMaxBillings = value;
    }

    /**
     * Gets the value of the mbRecurringFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRecurringFrequency() {
        return mbRecurringFrequency;
    }

    /**
     * Sets the value of the mbRecurringFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRecurringFrequency(String value) {
        this.mbRecurringFrequency = value;
    }

    /**
     * Gets the value of the mbDeferredBillDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBDeferredBillDate() {
        return mbDeferredBillDate;
    }

    /**
     * Sets the value of the mbDeferredBillDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBDeferredBillDate(String value) {
        this.mbDeferredBillDate = value;
    }

    /**
     * Gets the value of the mbMicroPaymentMaxDollarValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentMaxDollarValue() {
        return mbMicroPaymentMaxDollarValue;
    }

    /**
     * Sets the value of the mbMicroPaymentMaxDollarValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentMaxDollarValue(String value) {
        this.mbMicroPaymentMaxDollarValue = value;
    }

    /**
     * Gets the value of the mbMicroPaymentMaxBillingDays property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentMaxBillingDays() {
        return mbMicroPaymentMaxBillingDays;
    }

    /**
     * Sets the value of the mbMicroPaymentMaxBillingDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentMaxBillingDays(String value) {
        this.mbMicroPaymentMaxBillingDays = value;
    }

    /**
     * Gets the value of the mbMicroPaymentMaxTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentMaxTransactions() {
        return mbMicroPaymentMaxTransactions;
    }

    /**
     * Sets the value of the mbMicroPaymentMaxTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentMaxTransactions(String value) {
        this.mbMicroPaymentMaxTransactions = value;
    }

    /**
     * Gets the value of the mbCustomerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBCustomerStatus() {
        return mbCustomerStatus;
    }

    /**
     * Sets the value of the mbCustomerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBCustomerStatus(String value) {
        this.mbCustomerStatus = value;
    }

    /**
     * Gets the value of the mbMicroPaymentDaysLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentDaysLeft() {
        return mbMicroPaymentDaysLeft;
    }

    /**
     * Sets the value of the mbMicroPaymentDaysLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentDaysLeft(String value) {
        this.mbMicroPaymentDaysLeft = value;
    }

    /**
     * Gets the value of the mbMicroPaymentDollarsLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBMicroPaymentDollarsLeft() {
        return mbMicroPaymentDollarsLeft;
    }

    /**
     * Sets the value of the mbMicroPaymentDollarsLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBMicroPaymentDollarsLeft(String value) {
        this.mbMicroPaymentDollarsLeft = value;
    }

    /**
     * Gets the value of the euddCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDCountryCode() {
        return euddCountryCode;
    }

    /**
     * Sets the value of the euddCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDCountryCode(String value) {
        this.euddCountryCode = value;
    }

    /**
     * Gets the value of the euddBankSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankSortCode() {
        return euddBankSortCode;
    }

    /**
     * Sets the value of the euddBankSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankSortCode(String value) {
        this.euddBankSortCode = value;
    }

    /**
     * Gets the value of the euddRibCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDRibCode() {
        return euddRibCode;
    }

    /**
     * Sets the value of the euddRibCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDRibCode(String value) {
        this.euddRibCode = value;
    }

    /**
     * Gets the value of the sdMerchantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDMerchantName() {
        return sdMerchantName;
    }

    /**
     * Sets the value of the sdMerchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDMerchantName(String value) {
        this.sdMerchantName = value;
    }

    /**
     * Gets the value of the sdProductDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDProductDescription() {
        return sdProductDescription;
    }

    /**
     * Sets the value of the sdProductDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDProductDescription(String value) {
        this.sdProductDescription = value;
    }

    /**
     * Gets the value of the sdMerchantCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDMerchantCity() {
        return sdMerchantCity;
    }

    /**
     * Sets the value of the sdMerchantCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDMerchantCity(String value) {
        this.sdMerchantCity = value;
    }

    /**
     * Gets the value of the sdMerchantPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDMerchantPhone() {
        return sdMerchantPhone;
    }

    /**
     * Sets the value of the sdMerchantPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDMerchantPhone(String value) {
        this.sdMerchantPhone = value;
    }

    /**
     * Gets the value of the sdMerchantURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDMerchantURL() {
        return sdMerchantURL;
    }

    /**
     * Sets the value of the sdMerchantURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDMerchantURL(String value) {
        this.sdMerchantURL = value;
    }

    /**
     * Gets the value of the sdMerchantEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDMerchantEmail() {
        return sdMerchantEmail;
    }

    /**
     * Sets the value of the sdMerchantEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDMerchantEmail(String value) {
        this.sdMerchantEmail = value;
    }

    /**
     * Gets the value of the billerReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerReferenceNumber() {
        return billerReferenceNumber;
    }

    /**
     * Sets the value of the billerReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerReferenceNumber(String value) {
        this.billerReferenceNumber = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

    /**
     * Gets the value of the accountUpdaterEligibility property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountUpdaterEligibility() {
        return accountUpdaterEligibility;
    }

    /**
     * Sets the value of the accountUpdaterEligibility property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountUpdaterEligibility(String value) {
        this.accountUpdaterEligibility = value;
    }

    /**
     * Gets the value of the euddBankBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankBranchCode() {
        return euddBankBranchCode;
    }

    /**
     * Sets the value of the euddBankBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankBranchCode(String value) {
        this.euddBankBranchCode = value;
    }

    /**
     * Gets the value of the euddiban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDIBAN() {
        return euddiban;
    }

    /**
     * Sets the value of the euddiban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDIBAN(String value) {
        this.euddiban = value;
    }

    /**
     * Gets the value of the euddbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBIC() {
        return euddbic;
    }

    /**
     * Sets the value of the euddbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBIC(String value) {
        this.euddbic = value;
    }

    /**
     * Gets the value of the euddMandateSignatureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDMandateSignatureDate() {
        return euddMandateSignatureDate;
    }

    /**
     * Sets the value of the euddMandateSignatureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDMandateSignatureDate(String value) {
        this.euddMandateSignatureDate = value;
    }

    /**
     * Gets the value of the euddMandateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDMandateID() {
        return euddMandateID;
    }

    /**
     * Sets the value of the euddMandateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDMandateID(String value) {
        this.euddMandateID = value;
    }

    /**
     * Gets the value of the euddMandateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDMandateType() {
        return euddMandateType;
    }

    /**
     * Sets the value of the euddMandateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDMandateType(String value) {
        this.euddMandateType = value;
    }

    /**
     * Gets the value of the dpanInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDPANInd() {
        return dpanInd;
    }

    /**
     * Sets the value of the dpanInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDPANInd(String value) {
        this.dpanInd = value;
    }

    /**
     * Gets the value of the tokenRequestorID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenRequestorID() {
        return tokenRequestorID;
    }

    /**
     * Sets the value of the tokenRequestorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenRequestorID(String value) {
        this.tokenRequestorID = value;
    }

    /**
     * Gets the value of the mitMsgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITMsgType() {
        return mitMsgType;
    }

    /**
     * Sets the value of the mitMsgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITMsgType(String value) {
        this.mitMsgType = value;
    }

    /**
     * Gets the value of the mitSubmittedTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITSubmittedTransactionID() {
        return mitSubmittedTransactionID;
    }

    /**
     * Sets the value of the mitSubmittedTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITSubmittedTransactionID(String value) {
        this.mitSubmittedTransactionID = value;
    }

    /**
     * Gets the value of the pinlessDebitTxnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinlessDebitTxnType() {
        return pinlessDebitTxnType;
    }

    /**
     * Sets the value of the pinlessDebitTxnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinlessDebitTxnType(String value) {
        this.pinlessDebitTxnType = value;
    }

    /**
     * Gets the value of the pinlessDebitMerchantUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinlessDebitMerchantUrl() {
        return pinlessDebitMerchantUrl;
    }

    /**
     * Sets the value of the pinlessDebitMerchantUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinlessDebitMerchantUrl(String value) {
        this.pinlessDebitMerchantUrl = value;
    }

    /**
     * Gets the value of the safetechToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafetechToken() {
        return safetechToken;
    }

    /**
     * Sets the value of the safetechToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafetechToken(String value) {
        this.safetechToken = value;
    }

}
