//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for quickRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="quickRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartAccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxRefIdx" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApprovalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerBin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerMerchantID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerProfileAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProfileProcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerProfileMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerZIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerProfileOrderOverrideInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderDefaultDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderDefaultAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerAccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CCAccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CCExpireDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPAccountDDA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPAccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPAccountRT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPBankPmtDlv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SwitchSoloStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SwitchSoloIssueNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "quickRespType", propOrder = {
    "merchantID",
    "terminalID",
    "orderID",
    "accountNum",
    "startAccountNum",
    "txRefNum",
    "txRefIdx",
    "procStatus",
    "statusMsg",
    "approvalStatus",
    "customerBin",
    "customerMerchantID",
    "customerName",
    "customerRefNum",
    "customerProfileAction",
    "profileProcStatus",
    "customerProfileMessage",
    "customerAddress1",
    "customerAddress2",
    "customerCity",
    "customerState",
    "customerZIP",
    "customerEmail",
    "customerPhone",
    "customerProfileOrderOverrideInd",
    "orderDefaultDescription",
    "orderDefaultAmount",
    "customerAccountType",
    "ccAccountNum",
    "ccExpireDate",
    "ecpAccountDDA",
    "ecpAccountType",
    "ecpAccountRT",
    "ecpBankPmtDlv",
    "switchSoloStartDate",
    "switchSoloIssueNum",
    "respTime"
})
public class QuickRespType {

    @XmlElement(name = "MerchantID")
    protected String merchantID;
    @XmlElement(name = "TerminalID")
    protected String terminalID;
    @XmlElement(name = "OrderID")
    protected String orderID;
    @XmlElement(name = "AccountNum")
    protected String accountNum;
    @XmlElement(name = "StartAccountNum")
    protected String startAccountNum;
    @XmlElement(name = "TxRefNum")
    protected String txRefNum;
    @XmlElement(name = "TxRefIdx")
    protected String txRefIdx;
    @XmlElement(name = "ProcStatus", required = true)
    protected String procStatus;
    @XmlElement(name = "StatusMsg", required = true)
    protected String statusMsg;
    @XmlElement(name = "ApprovalStatus")
    protected String approvalStatus;
    @XmlElement(name = "CustomerBin")
    protected String customerBin;
    @XmlElement(name = "CustomerMerchantID")
    protected String customerMerchantID;
    @XmlElement(name = "CustomerName")
    protected String customerName;
    @XmlElement(name = "CustomerRefNum")
    protected String customerRefNum;
    @XmlElement(name = "CustomerProfileAction")
    protected String customerProfileAction;
    @XmlElement(name = "ProfileProcStatus")
    protected String profileProcStatus;
    @XmlElement(name = "CustomerProfileMessage")
    protected String customerProfileMessage;
    @XmlElement(name = "CustomerAddress1")
    protected String customerAddress1;
    @XmlElement(name = "CustomerAddress2")
    protected String customerAddress2;
    @XmlElement(name = "CustomerCity")
    protected String customerCity;
    @XmlElement(name = "CustomerState")
    protected String customerState;
    @XmlElement(name = "CustomerZIP")
    protected String customerZIP;
    @XmlElement(name = "CustomerEmail")
    protected String customerEmail;
    @XmlElement(name = "CustomerPhone")
    protected String customerPhone;
    @XmlElement(name = "CustomerProfileOrderOverrideInd")
    protected String customerProfileOrderOverrideInd;
    @XmlElement(name = "OrderDefaultDescription")
    protected String orderDefaultDescription;
    @XmlElement(name = "OrderDefaultAmount")
    protected String orderDefaultAmount;
    @XmlElement(name = "CustomerAccountType")
    protected String customerAccountType;
    @XmlElement(name = "CCAccountNum")
    protected String ccAccountNum;
    @XmlElement(name = "CCExpireDate")
    protected String ccExpireDate;
    @XmlElement(name = "ECPAccountDDA")
    protected String ecpAccountDDA;
    @XmlElement(name = "ECPAccountType")
    protected String ecpAccountType;
    @XmlElement(name = "ECPAccountRT")
    protected String ecpAccountRT;
    @XmlElement(name = "ECPBankPmtDlv")
    protected String ecpBankPmtDlv;
    @XmlElement(name = "SwitchSoloStartDate")
    protected String switchSoloStartDate;
    @XmlElement(name = "SwitchSoloIssueNum")
    protected String switchSoloIssueNum;
    @XmlElement(name = "RespTime")
    protected String respTime;

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the startAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAccountNum() {
        return startAccountNum;
    }

    /**
     * Sets the value of the startAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAccountNum(String value) {
        this.startAccountNum = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the txRefIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefIdx() {
        return txRefIdx;
    }

    /**
     * Sets the value of the txRefIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefIdx(String value) {
        this.txRefIdx = value;
    }

    /**
     * Gets the value of the procStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * Sets the value of the procStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcStatus(String value) {
        this.procStatus = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMsg(String value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the approvalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * Sets the value of the approvalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalStatus(String value) {
        this.approvalStatus = value;
    }

    /**
     * Gets the value of the customerBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerBin() {
        return customerBin;
    }

    /**
     * Sets the value of the customerBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerBin(String value) {
        this.customerBin = value;
    }

    /**
     * Gets the value of the customerMerchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMerchantID() {
        return customerMerchantID;
    }

    /**
     * Sets the value of the customerMerchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMerchantID(String value) {
        this.customerMerchantID = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the customerRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRefNum() {
        return customerRefNum;
    }

    /**
     * Sets the value of the customerRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRefNum(String value) {
        this.customerRefNum = value;
    }

    /**
     * Gets the value of the customerProfileAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileAction() {
        return customerProfileAction;
    }

    /**
     * Sets the value of the customerProfileAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileAction(String value) {
        this.customerProfileAction = value;
    }

    /**
     * Gets the value of the profileProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileProcStatus() {
        return profileProcStatus;
    }

    /**
     * Sets the value of the profileProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileProcStatus(String value) {
        this.profileProcStatus = value;
    }

    /**
     * Gets the value of the customerProfileMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileMessage() {
        return customerProfileMessage;
    }

    /**
     * Sets the value of the customerProfileMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileMessage(String value) {
        this.customerProfileMessage = value;
    }

    /**
     * Gets the value of the customerAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress1() {
        return customerAddress1;
    }

    /**
     * Sets the value of the customerAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress1(String value) {
        this.customerAddress1 = value;
    }

    /**
     * Gets the value of the customerAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAddress2() {
        return customerAddress2;
    }

    /**
     * Sets the value of the customerAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAddress2(String value) {
        this.customerAddress2 = value;
    }

    /**
     * Gets the value of the customerCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCity() {
        return customerCity;
    }

    /**
     * Sets the value of the customerCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCity(String value) {
        this.customerCity = value;
    }

    /**
     * Gets the value of the customerState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerState() {
        return customerState;
    }

    /**
     * Sets the value of the customerState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerState(String value) {
        this.customerState = value;
    }

    /**
     * Gets the value of the customerZIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerZIP() {
        return customerZIP;
    }

    /**
     * Sets the value of the customerZIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerZIP(String value) {
        this.customerZIP = value;
    }

    /**
     * Gets the value of the customerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the value of the customerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmail(String value) {
        this.customerEmail = value;
    }

    /**
     * Gets the value of the customerPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * Sets the value of the customerPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerPhone(String value) {
        this.customerPhone = value;
    }

    /**
     * Gets the value of the customerProfileOrderOverrideInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileOrderOverrideInd() {
        return customerProfileOrderOverrideInd;
    }

    /**
     * Sets the value of the customerProfileOrderOverrideInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileOrderOverrideInd(String value) {
        this.customerProfileOrderOverrideInd = value;
    }

    /**
     * Gets the value of the orderDefaultDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDefaultDescription() {
        return orderDefaultDescription;
    }

    /**
     * Sets the value of the orderDefaultDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDefaultDescription(String value) {
        this.orderDefaultDescription = value;
    }

    /**
     * Gets the value of the orderDefaultAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDefaultAmount() {
        return orderDefaultAmount;
    }

    /**
     * Sets the value of the orderDefaultAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDefaultAmount(String value) {
        this.orderDefaultAmount = value;
    }

    /**
     * Gets the value of the customerAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAccountType() {
        return customerAccountType;
    }

    /**
     * Sets the value of the customerAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAccountType(String value) {
        this.customerAccountType = value;
    }

    /**
     * Gets the value of the ccAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCAccountNum() {
        return ccAccountNum;
    }

    /**
     * Sets the value of the ccAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCAccountNum(String value) {
        this.ccAccountNum = value;
    }

    /**
     * Gets the value of the ccExpireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCExpireDate() {
        return ccExpireDate;
    }

    /**
     * Sets the value of the ccExpireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCExpireDate(String value) {
        this.ccExpireDate = value;
    }

    /**
     * Gets the value of the ecpAccountDDA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAccountDDA() {
        return ecpAccountDDA;
    }

    /**
     * Sets the value of the ecpAccountDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAccountDDA(String value) {
        this.ecpAccountDDA = value;
    }

    /**
     * Gets the value of the ecpAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAccountType() {
        return ecpAccountType;
    }

    /**
     * Sets the value of the ecpAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAccountType(String value) {
        this.ecpAccountType = value;
    }

    /**
     * Gets the value of the ecpAccountRT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAccountRT() {
        return ecpAccountRT;
    }

    /**
     * Sets the value of the ecpAccountRT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAccountRT(String value) {
        this.ecpAccountRT = value;
    }

    /**
     * Gets the value of the ecpBankPmtDlv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPBankPmtDlv() {
        return ecpBankPmtDlv;
    }

    /**
     * Sets the value of the ecpBankPmtDlv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPBankPmtDlv(String value) {
        this.ecpBankPmtDlv = value;
    }

    /**
     * Gets the value of the switchSoloStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchSoloStartDate() {
        return switchSoloStartDate;
    }

    /**
     * Sets the value of the switchSoloStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchSoloStartDate(String value) {
        this.switchSoloStartDate = value;
    }

    /**
     * Gets the value of the switchSoloIssueNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchSoloIssueNum() {
        return switchSoloIssueNum;
    }

    /**
     * Sets the value of the switchSoloIssueNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchSoloIssueNum(String value) {
        this.switchSoloIssueNum = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

}
