//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for quickRespType_old complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="quickRespType_old">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProcStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}StatusMsg" minOccurs="0"/>
 *         &lt;element name="ApprovalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxRefIdx" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="POSEntryMode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardType1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerProfileResponse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="HcsTcsInd" default="T">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="T"/>
 *             &lt;enumeration value="H"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MessageType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="FR"/>
 *             &lt;enumeration value="PR"/>
 *             &lt;enumeration value="V"/>
 *             &lt;enumeration value="A"/>
 *             &lt;enumeration value="AC"/>
 *             &lt;enumeration value="C"/>
 *             &lt;enumeration value="B"/>
 *             &lt;enumeration value="UC"/>
 *             &lt;enumeration value="U"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Version" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" fixed="2" />
 *       &lt;attribute name="CapStatus">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="0"/>
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="7"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LangInd" default="00">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value="00"/>
 *                 &lt;enumeration value="01"/>
 *                 &lt;enumeration value="02"/>
 *                 &lt;enumeration value="03"/>
 *                 &lt;enumeration value="04"/>
 *                 &lt;enumeration value="05"/>
 *                 &lt;enumeration value="06"/>
 *                 &lt;enumeration value="07"/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value=""/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="TzCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "quickRespType_old", propOrder = {
    "merchantID",
    "terminalID",
    "procStatus",
    "statusMsg",
    "approvalStatus",
    "txRefIdx",
    "txRefNum",
    "orderNumber",
    "accountNum",
    "posEntryMode",
    "cardType1",
    "respTime",
    "customerProfileResponse"
})
public class QuickRespTypeOld {

    @XmlElement(name = "MerchantID")
    protected String merchantID;
    @XmlElement(name = "TerminalID")
    protected String terminalID;
    @XmlElement(name = "ProcStatus")
    protected String procStatus;
    @XmlElement(name = "StatusMsg")
    protected StatusMsg statusMsg;
    @XmlElement(name = "ApprovalStatus")
    protected String approvalStatus;
    @XmlElement(name = "TxRefIdx")
    protected String txRefIdx;
    @XmlElement(name = "TxRefNum")
    protected String txRefNum;
    @XmlElement(name = "OrderNumber")
    protected String orderNumber;
    @XmlElement(name = "AccountNum")
    protected String accountNum;
    @XmlElement(name = "POSEntryMode")
    protected String posEntryMode;
    @XmlElement(name = "CardType1")
    protected String cardType1;
    @XmlElement(name = "RespTime")
    protected String respTime;
    @XmlElement(name = "CustomerProfileResponse")
    protected String customerProfileResponse;
    @XmlAttribute(name = "HcsTcsInd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String hcsTcsInd;
    @XmlAttribute(name = "MessageType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageType;
    @XmlAttribute(name = "Version")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String version;
    @XmlAttribute(name = "CapStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String capStatus;
    @XmlAttribute(name = "LangInd")
    protected String langInd;
    @XmlAttribute(name = "TzCode")
    protected String tzCode;

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the procStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * Sets the value of the procStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcStatus(String value) {
        this.procStatus = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link StatusMsg }
     *     
     */
    public StatusMsg getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusMsg }
     *     
     */
    public void setStatusMsg(StatusMsg value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the approvalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * Sets the value of the approvalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalStatus(String value) {
        this.approvalStatus = value;
    }

    /**
     * Gets the value of the txRefIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefIdx() {
        return txRefIdx;
    }

    /**
     * Sets the value of the txRefIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefIdx(String value) {
        this.txRefIdx = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the posEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSEntryMode() {
        return posEntryMode;
    }

    /**
     * Sets the value of the posEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSEntryMode(String value) {
        this.posEntryMode = value;
    }

    /**
     * Gets the value of the cardType1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardType1() {
        return cardType1;
    }

    /**
     * Sets the value of the cardType1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardType1(String value) {
        this.cardType1 = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

    /**
     * Gets the value of the customerProfileResponse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileResponse() {
        return customerProfileResponse;
    }

    /**
     * Sets the value of the customerProfileResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileResponse(String value) {
        this.customerProfileResponse = value;
    }

    /**
     * Gets the value of the hcsTcsInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHcsTcsInd() {
        if (hcsTcsInd == null) {
            return "T";
        } else {
            return hcsTcsInd;
        }
    }

    /**
     * Sets the value of the hcsTcsInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHcsTcsInd(String value) {
        this.hcsTcsInd = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageType(String value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "2";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the capStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapStatus() {
        return capStatus;
    }

    /**
     * Sets the value of the capStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapStatus(String value) {
        this.capStatus = value;
    }

    /**
     * Gets the value of the langInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLangInd() {
        if (langInd == null) {
            return "00";
        } else {
            return langInd;
        }
    }

    /**
     * Sets the value of the langInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLangInd(String value) {
        this.langInd = value;
    }

    /**
     * Gets the value of the tzCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTzCode() {
        return tzCode;
    }

    /**
     * Sets the value of the tzCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTzCode(String value) {
        this.tzCode = value;
    }

}
