//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reversalRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reversalRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefIdx" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OutstandingAmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MITReceivedTransactionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reversalRespType", propOrder = {
    "merchantID",
    "terminalID",
    "orderID",
    "txRefNum",
    "txRefIdx",
    "outstandingAmt",
    "procStatus",
    "statusMsg",
    "respTime",
    "mitReceivedTransactionID"
})
public class ReversalRespType {

    @XmlElement(name = "MerchantID", required = true)
    protected String merchantID;
    @XmlElement(name = "TerminalID", required = true)
    protected String terminalID;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "TxRefNum", required = true)
    protected String txRefNum;
    @XmlElement(name = "TxRefIdx", required = true)
    protected String txRefIdx;
    @XmlElement(name = "OutstandingAmt", required = true)
    protected String outstandingAmt;
    @XmlElement(name = "ProcStatus", required = true)
    protected String procStatus;
    @XmlElement(name = "StatusMsg", required = true)
    protected String statusMsg;
    @XmlElement(name = "RespTime", required = true)
    protected String respTime;
    @XmlElement(name = "MITReceivedTransactionID")
    protected String mitReceivedTransactionID;

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the txRefIdx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefIdx() {
        return txRefIdx;
    }

    /**
     * Sets the value of the txRefIdx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefIdx(String value) {
        this.txRefIdx = value;
    }

    /**
     * Gets the value of the outstandingAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutstandingAmt() {
        return outstandingAmt;
    }

    /**
     * Sets the value of the outstandingAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutstandingAmt(String value) {
        this.outstandingAmt = value;
    }

    /**
     * Gets the value of the procStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * Sets the value of the procStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcStatus(String value) {
        this.procStatus = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMsg(String value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

    /**
     * Gets the value of the mitReceivedTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMITReceivedTransactionID() {
        return mitReceivedTransactionID;
    }

    /**
     * Sets the value of the mitReceivedTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMITReceivedTransactionID(String value) {
        this.mitReceivedTransactionID = value;
    }

}
