//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:23 PM IST 
//


package com.medicalmine.charm.store.chase.bean.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for safetechFraudAnalysisRespType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="safetechFraudAnalysisRespType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndustryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TerminalID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CardBrand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ApprovalStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="StatusMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RespMsg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="HostRespCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProfileProcStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerProfileMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FraudAnalysisResponse" type="{}fraudAnalysisRespType"/>
 *         &lt;element name="EUDDCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankSortCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDRibCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "safetechFraudAnalysisRespType", propOrder = {
    "industryType",
    "merchantID",
    "terminalID",
    "cardBrand",
    "accountNum",
    "orderID",
    "txRefNum",
    "respTime",
    "procStatus",
    "approvalStatus",
    "respCode",
    "statusMsg",
    "respMsg",
    "hostRespCode",
    "customerRefNum",
    "customerName",
    "profileProcStatus",
    "customerProfileMessage",
    "fraudAnalysisResponse",
    "euddCountryCode",
    "euddBankSortCode",
    "euddRibCode",
    "euddBankBranchCode",
    "euddiban",
    "euddbic"
})
public class SafetechFraudAnalysisRespType {

    @XmlElement(name = "IndustryType", required = true)
    protected String industryType;
    @XmlElement(name = "MerchantID", required = true)
    protected String merchantID;
    @XmlElement(name = "TerminalID", required = true)
    protected String terminalID;
    @XmlElement(name = "CardBrand", required = true)
    protected String cardBrand;
    @XmlElement(name = "AccountNum", required = true)
    protected String accountNum;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "TxRefNum", required = true)
    protected String txRefNum;
    @XmlElement(name = "RespTime", required = true)
    protected String respTime;
    @XmlElement(name = "ProcStatus", required = true)
    protected String procStatus;
    @XmlElement(name = "ApprovalStatus", required = true)
    protected String approvalStatus;
    @XmlElement(name = "RespCode", required = true)
    protected String respCode;
    @XmlElement(name = "StatusMsg", required = true)
    protected String statusMsg;
    @XmlElement(name = "RespMsg", required = true)
    protected String respMsg;
    @XmlElement(name = "HostRespCode", required = true)
    protected String hostRespCode;
    @XmlElement(name = "CustomerRefNum", required = true)
    protected String customerRefNum;
    @XmlElement(name = "CustomerName", required = true)
    protected String customerName;
    @XmlElement(name = "ProfileProcStatus", required = true)
    protected String profileProcStatus;
    @XmlElement(name = "CustomerProfileMessage", required = true)
    protected String customerProfileMessage;
    @XmlElement(name = "FraudAnalysisResponse", required = true)
    protected FraudAnalysisRespType fraudAnalysisResponse;
    @XmlElement(name = "EUDDCountryCode")
    protected String euddCountryCode;
    @XmlElement(name = "EUDDBankSortCode")
    protected String euddBankSortCode;
    @XmlElement(name = "EUDDRibCode")
    protected String euddRibCode;
    @XmlElement(name = "EUDDBankBranchCode")
    protected String euddBankBranchCode;
    @XmlElement(name = "EUDDIBAN")
    protected String euddiban;
    @XmlElement(name = "EUDDBIC")
    protected String euddbic;

    /**
     * Gets the value of the industryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryType() {
        return industryType;
    }

    /**
     * Sets the value of the industryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryType(String value) {
        this.industryType = value;
    }

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the respTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespTime() {
        return respTime;
    }

    /**
     * Sets the value of the respTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespTime(String value) {
        this.respTime = value;
    }

    /**
     * Gets the value of the procStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * Sets the value of the procStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcStatus(String value) {
        this.procStatus = value;
    }

    /**
     * Gets the value of the approvalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalStatus() {
        return approvalStatus;
    }

    /**
     * Sets the value of the approvalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalStatus(String value) {
        this.approvalStatus = value;
    }

    /**
     * Gets the value of the respCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the statusMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusMsg() {
        return statusMsg;
    }

    /**
     * Sets the value of the statusMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusMsg(String value) {
        this.statusMsg = value;
    }

    /**
     * Gets the value of the respMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRespMsg() {
        return respMsg;
    }

    /**
     * Sets the value of the respMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRespMsg(String value) {
        this.respMsg = value;
    }

    /**
     * Gets the value of the hostRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostRespCode() {
        return hostRespCode;
    }

    /**
     * Sets the value of the hostRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostRespCode(String value) {
        this.hostRespCode = value;
    }

    /**
     * Gets the value of the customerRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRefNum() {
        return customerRefNum;
    }

    /**
     * Sets the value of the customerRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRefNum(String value) {
        this.customerRefNum = value;
    }

    /**
     * Gets the value of the customerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * Sets the value of the customerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerName(String value) {
        this.customerName = value;
    }

    /**
     * Gets the value of the profileProcStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileProcStatus() {
        return profileProcStatus;
    }

    /**
     * Sets the value of the profileProcStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileProcStatus(String value) {
        this.profileProcStatus = value;
    }

    /**
     * Gets the value of the customerProfileMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileMessage() {
        return customerProfileMessage;
    }

    /**
     * Sets the value of the customerProfileMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileMessage(String value) {
        this.customerProfileMessage = value;
    }

    /**
     * Gets the value of the fraudAnalysisResponse property.
     * 
     * @return
     *     possible object is
     *     {@link FraudAnalysisRespType }
     *     
     */
    public FraudAnalysisRespType getFraudAnalysisResponse() {
        return fraudAnalysisResponse;
    }

    /**
     * Sets the value of the fraudAnalysisResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudAnalysisRespType }
     *     
     */
    public void setFraudAnalysisResponse(FraudAnalysisRespType value) {
        this.fraudAnalysisResponse = value;
    }

    /**
     * Gets the value of the euddCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDCountryCode() {
        return euddCountryCode;
    }

    /**
     * Sets the value of the euddCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDCountryCode(String value) {
        this.euddCountryCode = value;
    }

    /**
     * Gets the value of the euddBankSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankSortCode() {
        return euddBankSortCode;
    }

    /**
     * Sets the value of the euddBankSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankSortCode(String value) {
        this.euddBankSortCode = value;
    }

    /**
     * Gets the value of the euddRibCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDRibCode() {
        return euddRibCode;
    }

    /**
     * Sets the value of the euddRibCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDRibCode(String value) {
        this.euddRibCode = value;
    }

    /**
     * Gets the value of the euddBankBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankBranchCode() {
        return euddBankBranchCode;
    }

    /**
     * Sets the value of the euddBankBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankBranchCode(String value) {
        this.euddBankBranchCode = value;
    }

    /**
     * Gets the value of the euddiban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDIBAN() {
        return euddiban;
    }

    /**
     * Sets the value of the euddiban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDIBAN(String value) {
        this.euddiban = value;
    }

    /**
     * Gets the value of the euddbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBIC() {
        return euddbic;
    }

    /**
     * Sets the value of the euddbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBIC(String value) {
        this.euddbic = value;
    }

}
