//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accountUpdaterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="accountUpdaterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrbitalConnectionUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrbitalConnectionPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerBin" type="{}valid-routing-bins"/>
 *         &lt;element name="CustomerMerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomerProfileAction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScheduledDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "accountUpdaterType", propOrder = {
    "orbitalConnectionUsername",
    "orbitalConnectionPassword",
    "customerBin",
    "customerMerchantID",
    "customerRefNum",
    "customerProfileAction",
    "scheduledDate"
})
public class AccountUpdaterType {

    @XmlElement(name = "OrbitalConnectionUsername")
    protected String orbitalConnectionUsername;
    @XmlElement(name = "OrbitalConnectionPassword")
    protected String orbitalConnectionPassword;
    @XmlElement(name = "CustomerBin", required = true)
    protected String customerBin;
    @XmlElement(name = "CustomerMerchantID", required = true)
    protected String customerMerchantID;
    @XmlElement(name = "CustomerRefNum", required = true)
    protected String customerRefNum;
    @XmlElement(name = "CustomerProfileAction")
    protected String customerProfileAction;
    @XmlElement(name = "ScheduledDate")
    protected String scheduledDate;

    /**
     * Gets the value of the orbitalConnectionUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalConnectionUsername() {
        return orbitalConnectionUsername;
    }

    /**
     * Sets the value of the orbitalConnectionUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalConnectionUsername(String value) {
        this.orbitalConnectionUsername = value;
    }

    /**
     * Gets the value of the orbitalConnectionPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalConnectionPassword() {
        return orbitalConnectionPassword;
    }

    /**
     * Sets the value of the orbitalConnectionPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalConnectionPassword(String value) {
        this.orbitalConnectionPassword = value;
    }

    /**
     * Gets the value of the customerBin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerBin() {
        return customerBin;
    }

    /**
     * Sets the value of the customerBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerBin(String value) {
        this.customerBin = value;
    }

    /**
     * Gets the value of the customerMerchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMerchantID() {
        return customerMerchantID;
    }

    /**
     * Sets the value of the customerMerchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMerchantID(String value) {
        this.customerMerchantID = value;
    }

    /**
     * Gets the value of the customerRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerRefNum() {
        return customerRefNum;
    }

    /**
     * Sets the value of the customerRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerRefNum(String value) {
        this.customerRefNum = value;
    }

    /**
     * Gets the value of the customerProfileAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerProfileAction() {
        return customerProfileAction;
    }

    /**
     * Sets the value of the customerProfileAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerProfileAction(String value) {
        this.customerProfileAction = value;
    }

    /**
     * Gets the value of the scheduledDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduledDate() {
        return scheduledDate;
    }

    /**
     * Sets the value of the scheduledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduledDate(String value) {
        this.scheduledDate = value;
    }

}
