//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baseElementsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseElementsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndustryType" type="{}valid-industry-types"/>
 *         &lt;element name="CardBrand" type="{}valid-card-brands" minOccurs="0"/>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Exp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CurrencyExponent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardSecValInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardSecVal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BCRtNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CheckDDA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BankAccountType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPAuthMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BankPmtDelv" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSzip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSaddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSaddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVScity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSstate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSphoneNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVScountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestzip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestaddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestaddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestcity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDeststate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestphoneNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestcountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UseCustomerRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuthenticationECIInd" type="{}valid-eci-types" minOccurs="0"/>
 *         &lt;element name="CAVV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="XID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AAV" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDCountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankSortCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDRibCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerIP" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLShippingCost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLTNCVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerRegistrationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerTypeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLItemCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLPreapprovalInvitationNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLMerchantPromotionalCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerBirthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerSSN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerAnnualIncome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerResidenceStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerCheckingAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLCustomerSavingsAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BMLProductDeliveryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BillerReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UseStoredAAVInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPCheckSerialNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPTerminalCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPTerminalState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECPImageReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerAni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerIpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddressSubtype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerBrowserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShippingMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBankBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EUDDBIC" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DWWalletID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DWSLI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DWIncentiveInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DigitalWalletType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseElementsType", propOrder = {
    "industryType",
    "cardBrand",
    "accountNum",
    "exp",
    "currencyCode",
    "currencyExponent",
    "cardSecValInd",
    "cardSecVal",
    "bcRtNum",
    "checkDDA",
    "bankAccountType",
    "ecpAuthMethod",
    "bankPmtDelv",
    "avSzip",
    "avSaddress1",
    "avSaddress2",
    "avScity",
    "avSstate",
    "avSphoneNum",
    "avSname",
    "avScountryCode",
    "avsDestzip",
    "avsDestaddress1",
    "avsDestaddress2",
    "avsDestcity",
    "avsDeststate",
    "avsDestphoneNum",
    "avsDestname",
    "avsDestcountryCode",
    "useCustomerRefNum",
    "authenticationECIInd",
    "cavv",
    "xid",
    "aav",
    "orderID",
    "amount",
    "comments",
    "euddCountryCode",
    "euddBankSortCode",
    "euddRibCode",
    "bmlCustomerIP",
    "bmlCustomerEmail",
    "bmlShippingCost",
    "bmltncVersion",
    "bmlCustomerRegistrationDate",
    "bmlCustomerTypeFlag",
    "bmlItemCategory",
    "bmlPreapprovalInvitationNum",
    "bmlMerchantPromotionalCode",
    "bmlCustomerBirthDate",
    "bmlCustomerSSN",
    "bmlCustomerAnnualIncome",
    "bmlCustomerResidenceStatus",
    "bmlCustomerCheckingAccount",
    "bmlCustomerSavingsAccount",
    "bmlProductDeliveryType",
    "billerReferenceNumber",
    "useStoredAAVInd",
    "ecpCheckSerialNumber",
    "ecpTerminalCity",
    "ecpTerminalState",
    "ecpImageReferenceNumber",
    "customerAni",
    "avsPhoneType",
    "avsDestPhoneType",
    "customerEmail",
    "customerIpAddress",
    "emailAddressSubtype",
    "customerBrowserName",
    "shippingMethod",
    "euddBankBranchCode",
    "euddiban",
    "euddbic",
    "dwWalletID",
    "dwsli",
    "dwIncentiveInd",
    "digitalWalletType"
})
public class BaseElementsType {

    @XmlElement(name = "IndustryType", required = true)
    @XmlSchemaType(name = "string")
    protected ValidIndustryTypes industryType;
    @XmlElement(name = "CardBrand")
    protected String cardBrand;
    @XmlElement(name = "AccountNum")
    protected String accountNum;
    @XmlElement(name = "Exp")
    protected String exp;
    @XmlElement(name = "CurrencyCode")
    protected String currencyCode;
    @XmlElement(name = "CurrencyExponent")
    protected String currencyExponent;
    @XmlElement(name = "CardSecValInd")
    protected String cardSecValInd;
    @XmlElement(name = "CardSecVal")
    protected String cardSecVal;
    @XmlElement(name = "BCRtNum")
    protected String bcRtNum;
    @XmlElement(name = "CheckDDA")
    protected String checkDDA;
    @XmlElement(name = "BankAccountType")
    protected String bankAccountType;
    @XmlElement(name = "ECPAuthMethod")
    protected String ecpAuthMethod;
    @XmlElement(name = "BankPmtDelv")
    protected String bankPmtDelv;
    @XmlElement(name = "AVSzip")
    protected String avSzip;
    @XmlElement(name = "AVSaddress1")
    protected String avSaddress1;
    @XmlElement(name = "AVSaddress2")
    protected String avSaddress2;
    @XmlElement(name = "AVScity")
    protected String avScity;
    @XmlElement(name = "AVSstate")
    protected String avSstate;
    @XmlElement(name = "AVSphoneNum")
    protected String avSphoneNum;
    @XmlElement(name = "AVSname")
    protected String avSname;
    @XmlElement(name = "AVScountryCode")
    protected String avScountryCode;
    @XmlElement(name = "AVSDestzip")
    protected String avsDestzip;
    @XmlElement(name = "AVSDestaddress1")
    protected String avsDestaddress1;
    @XmlElement(name = "AVSDestaddress2")
    protected String avsDestaddress2;
    @XmlElement(name = "AVSDestcity")
    protected String avsDestcity;
    @XmlElement(name = "AVSDeststate")
    protected String avsDeststate;
    @XmlElement(name = "AVSDestphoneNum")
    protected String avsDestphoneNum;
    @XmlElement(name = "AVSDestname")
    protected String avsDestname;
    @XmlElement(name = "AVSDestcountryCode")
    protected String avsDestcountryCode;
    @XmlElement(name = "UseCustomerRefNum")
    protected String useCustomerRefNum;
    @XmlElement(name = "AuthenticationECIInd")
    protected String authenticationECIInd;
    @XmlElement(name = "CAVV")
    protected String cavv;
    @XmlElement(name = "XID")
    protected String xid;
    @XmlElement(name = "AAV")
    protected String aav;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "Amount")
    protected String amount;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "EUDDCountryCode")
    protected String euddCountryCode;
    @XmlElement(name = "EUDDBankSortCode")
    protected String euddBankSortCode;
    @XmlElement(name = "EUDDRibCode")
    protected String euddRibCode;
    @XmlElement(name = "BMLCustomerIP")
    protected String bmlCustomerIP;
    @XmlElement(name = "BMLCustomerEmail")
    protected String bmlCustomerEmail;
    @XmlElement(name = "BMLShippingCost")
    protected String bmlShippingCost;
    @XmlElement(name = "BMLTNCVersion")
    protected String bmltncVersion;
    @XmlElement(name = "BMLCustomerRegistrationDate")
    protected String bmlCustomerRegistrationDate;
    @XmlElement(name = "BMLCustomerTypeFlag")
    protected String bmlCustomerTypeFlag;
    @XmlElement(name = "BMLItemCategory")
    protected String bmlItemCategory;
    @XmlElement(name = "BMLPreapprovalInvitationNum")
    protected String bmlPreapprovalInvitationNum;
    @XmlElement(name = "BMLMerchantPromotionalCode")
    protected String bmlMerchantPromotionalCode;
    @XmlElement(name = "BMLCustomerBirthDate")
    protected String bmlCustomerBirthDate;
    @XmlElement(name = "BMLCustomerSSN")
    protected String bmlCustomerSSN;
    @XmlElement(name = "BMLCustomerAnnualIncome")
    protected String bmlCustomerAnnualIncome;
    @XmlElement(name = "BMLCustomerResidenceStatus")
    protected String bmlCustomerResidenceStatus;
    @XmlElement(name = "BMLCustomerCheckingAccount")
    protected String bmlCustomerCheckingAccount;
    @XmlElement(name = "BMLCustomerSavingsAccount")
    protected String bmlCustomerSavingsAccount;
    @XmlElement(name = "BMLProductDeliveryType")
    protected String bmlProductDeliveryType;
    @XmlElement(name = "BillerReferenceNumber")
    protected String billerReferenceNumber;
    @XmlElement(name = "UseStoredAAVInd")
    protected String useStoredAAVInd;
    @XmlElement(name = "ECPCheckSerialNumber")
    protected String ecpCheckSerialNumber;
    @XmlElement(name = "ECPTerminalCity")
    protected String ecpTerminalCity;
    @XmlElement(name = "ECPTerminalState")
    protected String ecpTerminalState;
    @XmlElement(name = "ECPImageReferenceNumber")
    protected String ecpImageReferenceNumber;
    @XmlElement(name = "CustomerAni")
    protected String customerAni;
    @XmlElement(name = "AVSPhoneType")
    protected String avsPhoneType;
    @XmlElement(name = "AVSDestPhoneType")
    protected String avsDestPhoneType;
    @XmlElement(name = "CustomerEmail")
    protected String customerEmail;
    @XmlElement(name = "CustomerIpAddress")
    protected String customerIpAddress;
    @XmlElement(name = "EmailAddressSubtype")
    protected String emailAddressSubtype;
    @XmlElement(name = "CustomerBrowserName")
    protected String customerBrowserName;
    @XmlElement(name = "ShippingMethod")
    protected String shippingMethod;
    @XmlElement(name = "EUDDBankBranchCode")
    protected String euddBankBranchCode;
    @XmlElement(name = "EUDDIBAN")
    protected String euddiban;
    @XmlElement(name = "EUDDBIC")
    protected String euddbic;
    @XmlElement(name = "DWWalletID")
    protected String dwWalletID;
    @XmlElement(name = "DWSLI")
    protected String dwsli;
    @XmlElement(name = "DWIncentiveInd")
    protected String dwIncentiveInd;
    @XmlElement(name = "DigitalWalletType")
    protected String digitalWalletType;

    /**
     * Gets the value of the industryType property.
     * 
     * @return
     *     possible object is
     *     {@link ValidIndustryTypes }
     *     
     */
    public ValidIndustryTypes getIndustryType() {
        return industryType;
    }

    /**
     * Sets the value of the industryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidIndustryTypes }
     *     
     */
    public void setIndustryType(ValidIndustryTypes value) {
        this.industryType = value;
    }

    /**
     * Gets the value of the cardBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardBrand() {
        return cardBrand;
    }

    /**
     * Sets the value of the cardBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardBrand(String value) {
        this.cardBrand = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the exp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExp() {
        return exp;
    }

    /**
     * Sets the value of the exp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExp(String value) {
        this.exp = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the currencyExponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyExponent() {
        return currencyExponent;
    }

    /**
     * Sets the value of the currencyExponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyExponent(String value) {
        this.currencyExponent = value;
    }

    /**
     * Gets the value of the cardSecValInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardSecValInd() {
        return cardSecValInd;
    }

    /**
     * Sets the value of the cardSecValInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardSecValInd(String value) {
        this.cardSecValInd = value;
    }

    /**
     * Gets the value of the cardSecVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardSecVal() {
        return cardSecVal;
    }

    /**
     * Sets the value of the cardSecVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardSecVal(String value) {
        this.cardSecVal = value;
    }

    /**
     * Gets the value of the bcRtNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCRtNum() {
        return bcRtNum;
    }

    /**
     * Sets the value of the bcRtNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCRtNum(String value) {
        this.bcRtNum = value;
    }

    /**
     * Gets the value of the checkDDA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckDDA() {
        return checkDDA;
    }

    /**
     * Sets the value of the checkDDA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckDDA(String value) {
        this.checkDDA = value;
    }

    /**
     * Gets the value of the bankAccountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankAccountType() {
        return bankAccountType;
    }

    /**
     * Sets the value of the bankAccountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankAccountType(String value) {
        this.bankAccountType = value;
    }

    /**
     * Gets the value of the ecpAuthMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPAuthMethod() {
        return ecpAuthMethod;
    }

    /**
     * Sets the value of the ecpAuthMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPAuthMethod(String value) {
        this.ecpAuthMethod = value;
    }

    /**
     * Gets the value of the bankPmtDelv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankPmtDelv() {
        return bankPmtDelv;
    }

    /**
     * Sets the value of the bankPmtDelv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankPmtDelv(String value) {
        this.bankPmtDelv = value;
    }

    /**
     * Gets the value of the avSzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSzip() {
        return avSzip;
    }

    /**
     * Sets the value of the avSzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSzip(String value) {
        this.avSzip = value;
    }

    /**
     * Gets the value of the avSaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSaddress1() {
        return avSaddress1;
    }

    /**
     * Sets the value of the avSaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSaddress1(String value) {
        this.avSaddress1 = value;
    }

    /**
     * Gets the value of the avSaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSaddress2() {
        return avSaddress2;
    }

    /**
     * Sets the value of the avSaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSaddress2(String value) {
        this.avSaddress2 = value;
    }

    /**
     * Gets the value of the avScity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVScity() {
        return avScity;
    }

    /**
     * Sets the value of the avScity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVScity(String value) {
        this.avScity = value;
    }

    /**
     * Gets the value of the avSstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSstate() {
        return avSstate;
    }

    /**
     * Sets the value of the avSstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSstate(String value) {
        this.avSstate = value;
    }

    /**
     * Gets the value of the avSphoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSphoneNum() {
        return avSphoneNum;
    }

    /**
     * Sets the value of the avSphoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSphoneNum(String value) {
        this.avSphoneNum = value;
    }

    /**
     * Gets the value of the avSname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSname() {
        return avSname;
    }

    /**
     * Sets the value of the avSname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSname(String value) {
        this.avSname = value;
    }

    /**
     * Gets the value of the avScountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVScountryCode() {
        return avScountryCode;
    }

    /**
     * Sets the value of the avScountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVScountryCode(String value) {
        this.avScountryCode = value;
    }

    /**
     * Gets the value of the avsDestzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestzip() {
        return avsDestzip;
    }

    /**
     * Sets the value of the avsDestzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestzip(String value) {
        this.avsDestzip = value;
    }

    /**
     * Gets the value of the avsDestaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestaddress1() {
        return avsDestaddress1;
    }

    /**
     * Sets the value of the avsDestaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestaddress1(String value) {
        this.avsDestaddress1 = value;
    }

    /**
     * Gets the value of the avsDestaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestaddress2() {
        return avsDestaddress2;
    }

    /**
     * Sets the value of the avsDestaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestaddress2(String value) {
        this.avsDestaddress2 = value;
    }

    /**
     * Gets the value of the avsDestcity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestcity() {
        return avsDestcity;
    }

    /**
     * Sets the value of the avsDestcity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestcity(String value) {
        this.avsDestcity = value;
    }

    /**
     * Gets the value of the avsDeststate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDeststate() {
        return avsDeststate;
    }

    /**
     * Sets the value of the avsDeststate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDeststate(String value) {
        this.avsDeststate = value;
    }

    /**
     * Gets the value of the avsDestphoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestphoneNum() {
        return avsDestphoneNum;
    }

    /**
     * Sets the value of the avsDestphoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestphoneNum(String value) {
        this.avsDestphoneNum = value;
    }

    /**
     * Gets the value of the avsDestname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestname() {
        return avsDestname;
    }

    /**
     * Sets the value of the avsDestname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestname(String value) {
        this.avsDestname = value;
    }

    /**
     * Gets the value of the avsDestcountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestcountryCode() {
        return avsDestcountryCode;
    }

    /**
     * Sets the value of the avsDestcountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestcountryCode(String value) {
        this.avsDestcountryCode = value;
    }

    /**
     * Gets the value of the useCustomerRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseCustomerRefNum() {
        return useCustomerRefNum;
    }

    /**
     * Sets the value of the useCustomerRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseCustomerRefNum(String value) {
        this.useCustomerRefNum = value;
    }

    /**
     * Gets the value of the authenticationECIInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationECIInd() {
        return authenticationECIInd;
    }

    /**
     * Sets the value of the authenticationECIInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationECIInd(String value) {
        this.authenticationECIInd = value;
    }

    /**
     * Gets the value of the cavv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAVV() {
        return cavv;
    }

    /**
     * Sets the value of the cavv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAVV(String value) {
        this.cavv = value;
    }

    /**
     * Gets the value of the xid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXID() {
        return xid;
    }

    /**
     * Sets the value of the xid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXID(String value) {
        this.xid = value;
    }

    /**
     * Gets the value of the aav property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAAV() {
        return aav;
    }

    /**
     * Sets the value of the aav property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAAV(String value) {
        this.aav = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the euddCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDCountryCode() {
        return euddCountryCode;
    }

    /**
     * Sets the value of the euddCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDCountryCode(String value) {
        this.euddCountryCode = value;
    }

    /**
     * Gets the value of the euddBankSortCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankSortCode() {
        return euddBankSortCode;
    }

    /**
     * Sets the value of the euddBankSortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankSortCode(String value) {
        this.euddBankSortCode = value;
    }

    /**
     * Gets the value of the euddRibCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDRibCode() {
        return euddRibCode;
    }

    /**
     * Sets the value of the euddRibCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDRibCode(String value) {
        this.euddRibCode = value;
    }

    /**
     * Gets the value of the bmlCustomerIP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerIP() {
        return bmlCustomerIP;
    }

    /**
     * Sets the value of the bmlCustomerIP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerIP(String value) {
        this.bmlCustomerIP = value;
    }

    /**
     * Gets the value of the bmlCustomerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerEmail() {
        return bmlCustomerEmail;
    }

    /**
     * Sets the value of the bmlCustomerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerEmail(String value) {
        this.bmlCustomerEmail = value;
    }

    /**
     * Gets the value of the bmlShippingCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLShippingCost() {
        return bmlShippingCost;
    }

    /**
     * Sets the value of the bmlShippingCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLShippingCost(String value) {
        this.bmlShippingCost = value;
    }

    /**
     * Gets the value of the bmltncVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLTNCVersion() {
        return bmltncVersion;
    }

    /**
     * Sets the value of the bmltncVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLTNCVersion(String value) {
        this.bmltncVersion = value;
    }

    /**
     * Gets the value of the bmlCustomerRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerRegistrationDate() {
        return bmlCustomerRegistrationDate;
    }

    /**
     * Sets the value of the bmlCustomerRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerRegistrationDate(String value) {
        this.bmlCustomerRegistrationDate = value;
    }

    /**
     * Gets the value of the bmlCustomerTypeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerTypeFlag() {
        return bmlCustomerTypeFlag;
    }

    /**
     * Sets the value of the bmlCustomerTypeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerTypeFlag(String value) {
        this.bmlCustomerTypeFlag = value;
    }

    /**
     * Gets the value of the bmlItemCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLItemCategory() {
        return bmlItemCategory;
    }

    /**
     * Sets the value of the bmlItemCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLItemCategory(String value) {
        this.bmlItemCategory = value;
    }

    /**
     * Gets the value of the bmlPreapprovalInvitationNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLPreapprovalInvitationNum() {
        return bmlPreapprovalInvitationNum;
    }

    /**
     * Sets the value of the bmlPreapprovalInvitationNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLPreapprovalInvitationNum(String value) {
        this.bmlPreapprovalInvitationNum = value;
    }

    /**
     * Gets the value of the bmlMerchantPromotionalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLMerchantPromotionalCode() {
        return bmlMerchantPromotionalCode;
    }

    /**
     * Sets the value of the bmlMerchantPromotionalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLMerchantPromotionalCode(String value) {
        this.bmlMerchantPromotionalCode = value;
    }

    /**
     * Gets the value of the bmlCustomerBirthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerBirthDate() {
        return bmlCustomerBirthDate;
    }

    /**
     * Sets the value of the bmlCustomerBirthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerBirthDate(String value) {
        this.bmlCustomerBirthDate = value;
    }

    /**
     * Gets the value of the bmlCustomerSSN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerSSN() {
        return bmlCustomerSSN;
    }

    /**
     * Sets the value of the bmlCustomerSSN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerSSN(String value) {
        this.bmlCustomerSSN = value;
    }

    /**
     * Gets the value of the bmlCustomerAnnualIncome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerAnnualIncome() {
        return bmlCustomerAnnualIncome;
    }

    /**
     * Sets the value of the bmlCustomerAnnualIncome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerAnnualIncome(String value) {
        this.bmlCustomerAnnualIncome = value;
    }

    /**
     * Gets the value of the bmlCustomerResidenceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerResidenceStatus() {
        return bmlCustomerResidenceStatus;
    }

    /**
     * Sets the value of the bmlCustomerResidenceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerResidenceStatus(String value) {
        this.bmlCustomerResidenceStatus = value;
    }

    /**
     * Gets the value of the bmlCustomerCheckingAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerCheckingAccount() {
        return bmlCustomerCheckingAccount;
    }

    /**
     * Sets the value of the bmlCustomerCheckingAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerCheckingAccount(String value) {
        this.bmlCustomerCheckingAccount = value;
    }

    /**
     * Gets the value of the bmlCustomerSavingsAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLCustomerSavingsAccount() {
        return bmlCustomerSavingsAccount;
    }

    /**
     * Sets the value of the bmlCustomerSavingsAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLCustomerSavingsAccount(String value) {
        this.bmlCustomerSavingsAccount = value;
    }

    /**
     * Gets the value of the bmlProductDeliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBMLProductDeliveryType() {
        return bmlProductDeliveryType;
    }

    /**
     * Sets the value of the bmlProductDeliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBMLProductDeliveryType(String value) {
        this.bmlProductDeliveryType = value;
    }

    /**
     * Gets the value of the billerReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillerReferenceNumber() {
        return billerReferenceNumber;
    }

    /**
     * Sets the value of the billerReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillerReferenceNumber(String value) {
        this.billerReferenceNumber = value;
    }

    /**
     * Gets the value of the useStoredAAVInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseStoredAAVInd() {
        return useStoredAAVInd;
    }

    /**
     * Sets the value of the useStoredAAVInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseStoredAAVInd(String value) {
        this.useStoredAAVInd = value;
    }

    /**
     * Gets the value of the ecpCheckSerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPCheckSerialNumber() {
        return ecpCheckSerialNumber;
    }

    /**
     * Sets the value of the ecpCheckSerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPCheckSerialNumber(String value) {
        this.ecpCheckSerialNumber = value;
    }

    /**
     * Gets the value of the ecpTerminalCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPTerminalCity() {
        return ecpTerminalCity;
    }

    /**
     * Sets the value of the ecpTerminalCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPTerminalCity(String value) {
        this.ecpTerminalCity = value;
    }

    /**
     * Gets the value of the ecpTerminalState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPTerminalState() {
        return ecpTerminalState;
    }

    /**
     * Sets the value of the ecpTerminalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPTerminalState(String value) {
        this.ecpTerminalState = value;
    }

    /**
     * Gets the value of the ecpImageReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECPImageReferenceNumber() {
        return ecpImageReferenceNumber;
    }

    /**
     * Sets the value of the ecpImageReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECPImageReferenceNumber(String value) {
        this.ecpImageReferenceNumber = value;
    }

    /**
     * Gets the value of the customerAni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAni() {
        return customerAni;
    }

    /**
     * Sets the value of the customerAni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAni(String value) {
        this.customerAni = value;
    }

    /**
     * Gets the value of the avsPhoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSPhoneType() {
        return avsPhoneType;
    }

    /**
     * Sets the value of the avsPhoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSPhoneType(String value) {
        this.avsPhoneType = value;
    }

    /**
     * Gets the value of the avsDestPhoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestPhoneType() {
        return avsDestPhoneType;
    }

    /**
     * Sets the value of the avsDestPhoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestPhoneType(String value) {
        this.avsDestPhoneType = value;
    }

    /**
     * Gets the value of the customerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the value of the customerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmail(String value) {
        this.customerEmail = value;
    }

    /**
     * Gets the value of the customerIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerIpAddress() {
        return customerIpAddress;
    }

    /**
     * Sets the value of the customerIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerIpAddress(String value) {
        this.customerIpAddress = value;
    }

    /**
     * Gets the value of the emailAddressSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddressSubtype() {
        return emailAddressSubtype;
    }

    /**
     * Sets the value of the emailAddressSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddressSubtype(String value) {
        this.emailAddressSubtype = value;
    }

    /**
     * Gets the value of the customerBrowserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerBrowserName() {
        return customerBrowserName;
    }

    /**
     * Sets the value of the customerBrowserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerBrowserName(String value) {
        this.customerBrowserName = value;
    }

    /**
     * Gets the value of the shippingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingMethod() {
        return shippingMethod;
    }

    /**
     * Sets the value of the shippingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingMethod(String value) {
        this.shippingMethod = value;
    }

    /**
     * Gets the value of the euddBankBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBankBranchCode() {
        return euddBankBranchCode;
    }

    /**
     * Sets the value of the euddBankBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBankBranchCode(String value) {
        this.euddBankBranchCode = value;
    }

    /**
     * Gets the value of the euddiban property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDIBAN() {
        return euddiban;
    }

    /**
     * Sets the value of the euddiban property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDIBAN(String value) {
        this.euddiban = value;
    }

    /**
     * Gets the value of the euddbic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEUDDBIC() {
        return euddbic;
    }

    /**
     * Sets the value of the euddbic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEUDDBIC(String value) {
        this.euddbic = value;
    }

    /**
     * Gets the value of the dwWalletID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDWWalletID() {
        return dwWalletID;
    }

    /**
     * Sets the value of the dwWalletID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDWWalletID(String value) {
        this.dwWalletID = value;
    }

    /**
     * Gets the value of the dwsli property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDWSLI() {
        return dwsli;
    }

    /**
     * Sets the value of the dwsli property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDWSLI(String value) {
        this.dwsli = value;
    }

    /**
     * Gets the value of the dwIncentiveInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDWIncentiveInd() {
        return dwIncentiveInd;
    }

    /**
     * Sets the value of the dwIncentiveInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDWIncentiveInd(String value) {
        this.dwIncentiveInd = value;
    }

    /**
     * Gets the value of the digitalWalletType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitalWalletType() {
        return digitalWalletType;
    }

    /**
     * Sets the value of the digitalWalletType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitalWalletType(String value) {
        this.digitalWalletType = value;
    }

}
