//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flexCacheType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="flexCacheType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrbitalConnectionUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrbitalConnectionPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BIN" type="{}valid-routing-bins"/>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TerminalID" type="{}terminal-type"/>
 *         &lt;element name="AccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardSecVal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShippingRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndustryType" type="{}valid-industry-types"/>
 *         &lt;element name="FlexAutoAuthInd" type="{}yes-or-no"/>
 *         &lt;element name="FlexPartialRedemptionInd" type="{}yes-or-no"/>
 *         &lt;element name="FlexAction" type="{}flex-action-types"/>
 *         &lt;element name="StartAccountNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ActivationCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FlexEmployeeNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PriorAuthID" type="{}vallid-prior-auth" minOccurs="0"/>
 *         &lt;element name="AVSzip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSaddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSaddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVScity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSstate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSphoneNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVScountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestzip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestaddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestaddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestcity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDeststate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestphoneNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestcountryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerAni" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AVSDestPhoneType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerIpAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddressSubtype" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerBrowserName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShippingMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudAnalysis" type="{}fraudAnalysisType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "flexCacheType", propOrder = {
    "orbitalConnectionUsername",
    "orbitalConnectionPassword",
    "bin",
    "merchantID",
    "terminalID",
    "accountNum",
    "orderID",
    "amount",
    "cardSecVal",
    "comments",
    "shippingRef",
    "industryType",
    "flexAutoAuthInd",
    "flexPartialRedemptionInd",
    "flexAction",
    "startAccountNum",
    "activationCount",
    "txRefNum",
    "flexEmployeeNumber",
    "priorAuthID",
    "avSzip",
    "avSaddress1",
    "avSaddress2",
    "avScity",
    "avSstate",
    "avSphoneNum",
    "avSname",
    "avScountryCode",
    "avsDestzip",
    "avsDestaddress1",
    "avsDestaddress2",
    "avsDestcity",
    "avsDeststate",
    "avsDestphoneNum",
    "avsDestname",
    "avsDestcountryCode",
    "customerAni",
    "avsPhoneType",
    "avsDestPhoneType",
    "customerEmail",
    "customerIpAddress",
    "emailAddressSubtype",
    "customerBrowserName",
    "shippingMethod",
    "fraudAnalysis"
})
public class FlexCacheType {

    @XmlElement(name = "OrbitalConnectionUsername")
    protected String orbitalConnectionUsername;
    @XmlElement(name = "OrbitalConnectionPassword")
    protected String orbitalConnectionPassword;
    @XmlElement(name = "BIN", required = true)
    protected String bin;
    @XmlElement(name = "MerchantID", required = true)
    protected String merchantID;
    @XmlElement(name = "TerminalID", required = true)
    protected String terminalID;
    @XmlElement(name = "AccountNum")
    protected String accountNum;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "Amount")
    protected String amount;
    @XmlElement(name = "CardSecVal")
    protected String cardSecVal;
    @XmlElement(name = "Comments")
    protected String comments;
    @XmlElement(name = "ShippingRef")
    protected String shippingRef;
    @XmlElement(name = "IndustryType", required = true)
    @XmlSchemaType(name = "string")
    protected ValidIndustryTypes industryType;
    @XmlElement(name = "FlexAutoAuthInd", required = true)
    protected String flexAutoAuthInd;
    @XmlElement(name = "FlexPartialRedemptionInd", required = true)
    protected String flexPartialRedemptionInd;
    @XmlElement(name = "FlexAction", required = true)
    protected String flexAction;
    @XmlElement(name = "StartAccountNum")
    protected String startAccountNum;
    @XmlElement(name = "ActivationCount")
    protected String activationCount;
    @XmlElement(name = "TxRefNum")
    protected String txRefNum;
    @XmlElement(name = "FlexEmployeeNumber")
    protected String flexEmployeeNumber;
    @XmlElement(name = "PriorAuthID")
    protected String priorAuthID;
    @XmlElement(name = "AVSzip")
    protected String avSzip;
    @XmlElement(name = "AVSaddress1")
    protected String avSaddress1;
    @XmlElement(name = "AVSaddress2")
    protected String avSaddress2;
    @XmlElement(name = "AVScity")
    protected String avScity;
    @XmlElement(name = "AVSstate")
    protected String avSstate;
    @XmlElement(name = "AVSphoneNum")
    protected String avSphoneNum;
    @XmlElement(name = "AVSname")
    protected String avSname;
    @XmlElement(name = "AVScountryCode")
    protected String avScountryCode;
    @XmlElement(name = "AVSDestzip")
    protected String avsDestzip;
    @XmlElement(name = "AVSDestaddress1")
    protected String avsDestaddress1;
    @XmlElement(name = "AVSDestaddress2")
    protected String avsDestaddress2;
    @XmlElement(name = "AVSDestcity")
    protected String avsDestcity;
    @XmlElement(name = "AVSDeststate")
    protected String avsDeststate;
    @XmlElement(name = "AVSDestphoneNum")
    protected String avsDestphoneNum;
    @XmlElement(name = "AVSDestname")
    protected String avsDestname;
    @XmlElement(name = "AVSDestcountryCode")
    protected String avsDestcountryCode;
    @XmlElement(name = "CustomerAni")
    protected String customerAni;
    @XmlElement(name = "AVSPhoneType")
    protected String avsPhoneType;
    @XmlElement(name = "AVSDestPhoneType")
    protected String avsDestPhoneType;
    @XmlElement(name = "CustomerEmail")
    protected String customerEmail;
    @XmlElement(name = "CustomerIpAddress")
    protected String customerIpAddress;
    @XmlElement(name = "EmailAddressSubtype")
    protected String emailAddressSubtype;
    @XmlElement(name = "CustomerBrowserName")
    protected String customerBrowserName;
    @XmlElement(name = "ShippingMethod")
    protected String shippingMethod;
    @XmlElement(name = "FraudAnalysis")
    protected FraudAnalysisType fraudAnalysis;

    /**
     * Gets the value of the orbitalConnectionUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalConnectionUsername() {
        return orbitalConnectionUsername;
    }

    /**
     * Sets the value of the orbitalConnectionUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalConnectionUsername(String value) {
        this.orbitalConnectionUsername = value;
    }

    /**
     * Gets the value of the orbitalConnectionPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalConnectionPassword() {
        return orbitalConnectionPassword;
    }

    /**
     * Sets the value of the orbitalConnectionPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalConnectionPassword(String value) {
        this.orbitalConnectionPassword = value;
    }

    /**
     * Gets the value of the bin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIN() {
        return bin;
    }

    /**
     * Sets the value of the bin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIN(String value) {
        this.bin = value;
    }

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the accountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * Sets the value of the accountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNum(String value) {
        this.accountNum = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the cardSecVal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardSecVal() {
        return cardSecVal;
    }

    /**
     * Sets the value of the cardSecVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardSecVal(String value) {
        this.cardSecVal = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the shippingRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingRef() {
        return shippingRef;
    }

    /**
     * Sets the value of the shippingRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingRef(String value) {
        this.shippingRef = value;
    }

    /**
     * Gets the value of the industryType property.
     * 
     * @return
     *     possible object is
     *     {@link ValidIndustryTypes }
     *     
     */
    public ValidIndustryTypes getIndustryType() {
        return industryType;
    }

    /**
     * Sets the value of the industryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidIndustryTypes }
     *     
     */
    public void setIndustryType(ValidIndustryTypes value) {
        this.industryType = value;
    }

    /**
     * Gets the value of the flexAutoAuthInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexAutoAuthInd() {
        return flexAutoAuthInd;
    }

    /**
     * Sets the value of the flexAutoAuthInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexAutoAuthInd(String value) {
        this.flexAutoAuthInd = value;
    }

    /**
     * Gets the value of the flexPartialRedemptionInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexPartialRedemptionInd() {
        return flexPartialRedemptionInd;
    }

    /**
     * Sets the value of the flexPartialRedemptionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexPartialRedemptionInd(String value) {
        this.flexPartialRedemptionInd = value;
    }

    /**
     * Gets the value of the flexAction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexAction() {
        return flexAction;
    }

    /**
     * Sets the value of the flexAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexAction(String value) {
        this.flexAction = value;
    }

    /**
     * Gets the value of the startAccountNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartAccountNum() {
        return startAccountNum;
    }

    /**
     * Sets the value of the startAccountNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartAccountNum(String value) {
        this.startAccountNum = value;
    }

    /**
     * Gets the value of the activationCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationCount() {
        return activationCount;
    }

    /**
     * Sets the value of the activationCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationCount(String value) {
        this.activationCount = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the flexEmployeeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlexEmployeeNumber() {
        return flexEmployeeNumber;
    }

    /**
     * Sets the value of the flexEmployeeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlexEmployeeNumber(String value) {
        this.flexEmployeeNumber = value;
    }

    /**
     * Gets the value of the priorAuthID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorAuthID() {
        return priorAuthID;
    }

    /**
     * Sets the value of the priorAuthID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorAuthID(String value) {
        this.priorAuthID = value;
    }

    /**
     * Gets the value of the avSzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSzip() {
        return avSzip;
    }

    /**
     * Sets the value of the avSzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSzip(String value) {
        this.avSzip = value;
    }

    /**
     * Gets the value of the avSaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSaddress1() {
        return avSaddress1;
    }

    /**
     * Sets the value of the avSaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSaddress1(String value) {
        this.avSaddress1 = value;
    }

    /**
     * Gets the value of the avSaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSaddress2() {
        return avSaddress2;
    }

    /**
     * Sets the value of the avSaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSaddress2(String value) {
        this.avSaddress2 = value;
    }

    /**
     * Gets the value of the avScity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVScity() {
        return avScity;
    }

    /**
     * Sets the value of the avScity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVScity(String value) {
        this.avScity = value;
    }

    /**
     * Gets the value of the avSstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSstate() {
        return avSstate;
    }

    /**
     * Sets the value of the avSstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSstate(String value) {
        this.avSstate = value;
    }

    /**
     * Gets the value of the avSphoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSphoneNum() {
        return avSphoneNum;
    }

    /**
     * Sets the value of the avSphoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSphoneNum(String value) {
        this.avSphoneNum = value;
    }

    /**
     * Gets the value of the avSname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSname() {
        return avSname;
    }

    /**
     * Sets the value of the avSname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSname(String value) {
        this.avSname = value;
    }

    /**
     * Gets the value of the avScountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVScountryCode() {
        return avScountryCode;
    }

    /**
     * Sets the value of the avScountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVScountryCode(String value) {
        this.avScountryCode = value;
    }

    /**
     * Gets the value of the avsDestzip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestzip() {
        return avsDestzip;
    }

    /**
     * Sets the value of the avsDestzip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestzip(String value) {
        this.avsDestzip = value;
    }

    /**
     * Gets the value of the avsDestaddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestaddress1() {
        return avsDestaddress1;
    }

    /**
     * Sets the value of the avsDestaddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestaddress1(String value) {
        this.avsDestaddress1 = value;
    }

    /**
     * Gets the value of the avsDestaddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestaddress2() {
        return avsDestaddress2;
    }

    /**
     * Sets the value of the avsDestaddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestaddress2(String value) {
        this.avsDestaddress2 = value;
    }

    /**
     * Gets the value of the avsDestcity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestcity() {
        return avsDestcity;
    }

    /**
     * Sets the value of the avsDestcity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestcity(String value) {
        this.avsDestcity = value;
    }

    /**
     * Gets the value of the avsDeststate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDeststate() {
        return avsDeststate;
    }

    /**
     * Sets the value of the avsDeststate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDeststate(String value) {
        this.avsDeststate = value;
    }

    /**
     * Gets the value of the avsDestphoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestphoneNum() {
        return avsDestphoneNum;
    }

    /**
     * Sets the value of the avsDestphoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestphoneNum(String value) {
        this.avsDestphoneNum = value;
    }

    /**
     * Gets the value of the avsDestname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestname() {
        return avsDestname;
    }

    /**
     * Sets the value of the avsDestname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestname(String value) {
        this.avsDestname = value;
    }

    /**
     * Gets the value of the avsDestcountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestcountryCode() {
        return avsDestcountryCode;
    }

    /**
     * Sets the value of the avsDestcountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestcountryCode(String value) {
        this.avsDestcountryCode = value;
    }

    /**
     * Gets the value of the customerAni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerAni() {
        return customerAni;
    }

    /**
     * Sets the value of the customerAni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerAni(String value) {
        this.customerAni = value;
    }

    /**
     * Gets the value of the avsPhoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSPhoneType() {
        return avsPhoneType;
    }

    /**
     * Sets the value of the avsPhoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSPhoneType(String value) {
        this.avsPhoneType = value;
    }

    /**
     * Gets the value of the avsDestPhoneType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVSDestPhoneType() {
        return avsDestPhoneType;
    }

    /**
     * Sets the value of the avsDestPhoneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVSDestPhoneType(String value) {
        this.avsDestPhoneType = value;
    }

    /**
     * Gets the value of the customerEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * Sets the value of the customerEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerEmail(String value) {
        this.customerEmail = value;
    }

    /**
     * Gets the value of the customerIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerIpAddress() {
        return customerIpAddress;
    }

    /**
     * Sets the value of the customerIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerIpAddress(String value) {
        this.customerIpAddress = value;
    }

    /**
     * Gets the value of the emailAddressSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddressSubtype() {
        return emailAddressSubtype;
    }

    /**
     * Sets the value of the emailAddressSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddressSubtype(String value) {
        this.emailAddressSubtype = value;
    }

    /**
     * Gets the value of the customerBrowserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerBrowserName() {
        return customerBrowserName;
    }

    /**
     * Sets the value of the customerBrowserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerBrowserName(String value) {
        this.customerBrowserName = value;
    }

    /**
     * Gets the value of the shippingMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingMethod() {
        return shippingMethod;
    }

    /**
     * Sets the value of the shippingMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingMethod(String value) {
        this.shippingMethod = value;
    }

    /**
     * Gets the value of the fraudAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link FraudAnalysisType }
     *     
     */
    public FraudAnalysisType getFraudAnalysis() {
        return fraudAnalysis;
    }

    /**
     * Sets the value of the fraudAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudAnalysisType }
     *     
     */
    public void setFraudAnalysis(FraudAnalysisType value) {
        this.fraudAnalysis = value;
    }

}
