//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fraudAnalysisType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fraudAnalysisType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FraudScoreIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RulesTrigger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SafetechMerchantID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KaptchaSessionID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WebsiteShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CashValueOfFencibleItems" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerDOB" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerGender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerDriverLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerIDCreationTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KTTVersionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KTTDataLength" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KTTDataString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PinlessDebitTxnType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PinlessDebitMerchantUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fraudAnalysisType", propOrder = {
    "fraudScoreIndicator",
    "rulesTrigger",
    "safetechMerchantID",
    "kaptchaSessionID",
    "websiteShortName",
    "cashValueOfFencibleItems",
    "customerDOB",
    "customerGender",
    "customerDriverLicense",
    "customerID",
    "customerIDCreationTime",
    "kttVersionNumber",
    "kttDataLength",
    "kttDataString",
    "pinlessDebitTxnType",
    "pinlessDebitMerchantUrl"
})
public class FraudAnalysisType {

    @XmlElement(name = "FraudScoreIndicator")
    protected String fraudScoreIndicator;
    @XmlElement(name = "RulesTrigger")
    protected String rulesTrigger;
    @XmlElement(name = "SafetechMerchantID")
    protected String safetechMerchantID;
    @XmlElement(name = "KaptchaSessionID")
    protected String kaptchaSessionID;
    @XmlElement(name = "WebsiteShortName")
    protected String websiteShortName;
    @XmlElement(name = "CashValueOfFencibleItems")
    protected String cashValueOfFencibleItems;
    @XmlElement(name = "CustomerDOB")
    protected String customerDOB;
    @XmlElement(name = "CustomerGender")
    protected String customerGender;
    @XmlElement(name = "CustomerDriverLicense")
    protected String customerDriverLicense;
    @XmlElement(name = "CustomerID")
    protected String customerID;
    @XmlElement(name = "CustomerIDCreationTime")
    protected String customerIDCreationTime;
    @XmlElement(name = "KTTVersionNumber")
    protected String kttVersionNumber;
    @XmlElement(name = "KTTDataLength")
    protected String kttDataLength;
    @XmlElement(name = "KTTDataString")
    protected String kttDataString;
    @XmlElement(name = "PinlessDebitTxnType")
    protected String pinlessDebitTxnType;
    @XmlElement(name = "PinlessDebitMerchantUrl")
    protected String pinlessDebitMerchantUrl;

    /**
     * Gets the value of the fraudScoreIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudScoreIndicator() {
        return fraudScoreIndicator;
    }

    /**
     * Sets the value of the fraudScoreIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudScoreIndicator(String value) {
        this.fraudScoreIndicator = value;
    }

    /**
     * Gets the value of the rulesTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRulesTrigger() {
        return rulesTrigger;
    }

    /**
     * Sets the value of the rulesTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRulesTrigger(String value) {
        this.rulesTrigger = value;
    }

    /**
     * Gets the value of the safetechMerchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSafetechMerchantID() {
        return safetechMerchantID;
    }

    /**
     * Sets the value of the safetechMerchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSafetechMerchantID(String value) {
        this.safetechMerchantID = value;
    }

    /**
     * Gets the value of the kaptchaSessionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKaptchaSessionID() {
        return kaptchaSessionID;
    }

    /**
     * Sets the value of the kaptchaSessionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKaptchaSessionID(String value) {
        this.kaptchaSessionID = value;
    }

    /**
     * Gets the value of the websiteShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsiteShortName() {
        return websiteShortName;
    }

    /**
     * Sets the value of the websiteShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsiteShortName(String value) {
        this.websiteShortName = value;
    }

    /**
     * Gets the value of the cashValueOfFencibleItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashValueOfFencibleItems() {
        return cashValueOfFencibleItems;
    }

    /**
     * Sets the value of the cashValueOfFencibleItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashValueOfFencibleItems(String value) {
        this.cashValueOfFencibleItems = value;
    }

    /**
     * Gets the value of the customerDOB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerDOB() {
        return customerDOB;
    }

    /**
     * Sets the value of the customerDOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerDOB(String value) {
        this.customerDOB = value;
    }

    /**
     * Gets the value of the customerGender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerGender() {
        return customerGender;
    }

    /**
     * Sets the value of the customerGender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerGender(String value) {
        this.customerGender = value;
    }

    /**
     * Gets the value of the customerDriverLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerDriverLicense() {
        return customerDriverLicense;
    }

    /**
     * Sets the value of the customerDriverLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerDriverLicense(String value) {
        this.customerDriverLicense = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the customerIDCreationTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerIDCreationTime() {
        return customerIDCreationTime;
    }

    /**
     * Sets the value of the customerIDCreationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerIDCreationTime(String value) {
        this.customerIDCreationTime = value;
    }

    /**
     * Gets the value of the kttVersionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKTTVersionNumber() {
        return kttVersionNumber;
    }

    /**
     * Sets the value of the kttVersionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKTTVersionNumber(String value) {
        this.kttVersionNumber = value;
    }

    /**
     * Gets the value of the kttDataLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKTTDataLength() {
        return kttDataLength;
    }

    /**
     * Sets the value of the kttDataLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKTTDataLength(String value) {
        this.kttDataLength = value;
    }

    /**
     * Gets the value of the kttDataString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKTTDataString() {
        return kttDataString;
    }

    /**
     * Sets the value of the kttDataString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKTTDataString(String value) {
        this.kttDataString = value;
    }

    /**
     * Gets the value of the pinlessDebitTxnType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinlessDebitTxnType() {
        return pinlessDebitTxnType;
    }

    /**
     * Sets the value of the pinlessDebitTxnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinlessDebitTxnType(String value) {
        this.pinlessDebitTxnType = value;
    }

    /**
     * Gets the value of the pinlessDebitMerchantUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinlessDebitMerchantUrl() {
        return pinlessDebitMerchantUrl;
    }

    /**
     * Sets the value of the pinlessDebitMerchantUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinlessDebitMerchantUrl(String value) {
        this.pinlessDebitMerchantUrl = value;
    }

}
