//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for markForCaptureType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="markForCaptureType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrbitalConnectionUsername" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrbitalConnectionPassword" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrderID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxInd" type="{}valid-tax-inds" minOccurs="0"/>
 *         &lt;element name="Tax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BIN" type="{}valid-routing-bins"/>
 *         &lt;element name="MerchantID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TerminalID" type="{}terminal-type"/>
 *         &lt;element name="TxRefNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PCOrderNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCDestZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCDestName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCDestAddress1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCDestAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCDestCity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCDestState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMEXTranAdvAddn1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMEXTranAdvAddn2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMEXTranAdvAddn3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMEXTranAdvAddn4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3FreightAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DutyAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DestCountryCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3ShipFromZip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DiscAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3VATtaxAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3VATtaxRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3AltTaxInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3AltTaxID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3AltTaxAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3LineItemCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3LineItemArray" type="{}PC3LineItemArray" minOccurs="0"/>
 *         &lt;element name="PCardRequestorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardLocalTaxRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardNationalTax" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardPstTaxRegNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardCustomerVatRegNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardMerchantVatRegNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardTotalTaxAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardDtlTaxAmount1Ind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardDtlTaxAmount1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardDtlTaxAmount2Ind" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PCardDtlTaxAmount2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PinlessDebitTotalShpmnt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuthenticationECIInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DigitalTokenCryptogram" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="XID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCATrustedMerchant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCASecureCorporatePayment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCATransactionRiskAnalysis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCALowValuePayment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCAMerchantInitiatedTransaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCARecurringPayment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SCADelegation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MCProgramProtocol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MCDirectoryTransID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UCAFInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "markForCaptureType", propOrder = {
    "orbitalConnectionUsername",
    "orbitalConnectionPassword",
    "orderID",
    "amount",
    "taxInd",
    "tax",
    "bin",
    "merchantID",
    "terminalID",
    "txRefNum",
    "pcOrderNum",
    "pcDestZip",
    "pcDestName",
    "pcDestAddress1",
    "pcDestAddress2",
    "pcDestCity",
    "pcDestState",
    "amexTranAdvAddn1",
    "amexTranAdvAddn2",
    "amexTranAdvAddn3",
    "amexTranAdvAddn4",
    "pc3FreightAmt",
    "pc3DutyAmt",
    "pc3DestCountryCd",
    "pc3ShipFromZip",
    "pc3DiscAmt",
    "pc3VATtaxAmt",
    "pc3VATtaxRate",
    "pc3AltTaxInd",
    "pc3AltTaxID",
    "pc3AltTaxAmt",
    "pc3LineItemCount",
    "pc3LineItemArray",
    "pCardRequestorName",
    "pCardLocalTaxRate",
    "pCardNationalTax",
    "pCardPstTaxRegNumber",
    "pCardCustomerVatRegNumber",
    "pCardMerchantVatRegNumber",
    "pCardTotalTaxAmount",
    "pCardDtlTaxAmount1Ind",
    "pCardDtlTaxAmount1",
    "pCardDtlTaxAmount2Ind",
    "pCardDtlTaxAmount2",
    "pinlessDebitTotalShpmnt",
    "authenticationECIInd",
    "digitalTokenCryptogram",
    "xid",
    "scaTrustedMerchant",
    "scaSecureCorporatePayment",
    "scaTransactionRiskAnalysis",
    "scaLowValuePayment",
    "scaMerchantInitiatedTransaction",
    "scaRecurringPayment",
    "scaDelegation",
    "mcProgramProtocol",
    "mcDirectoryTransID",
    "ucafInd"
})
public class MarkForCaptureType {

    @XmlElement(name = "OrbitalConnectionUsername")
    protected String orbitalConnectionUsername;
    @XmlElement(name = "OrbitalConnectionPassword")
    protected String orbitalConnectionPassword;
    @XmlElement(name = "OrderID", required = true)
    protected String orderID;
    @XmlElement(name = "Amount")
    protected String amount;
    @XmlElement(name = "TaxInd")
    protected String taxInd;
    @XmlElement(name = "Tax")
    protected String tax;
    @XmlElement(name = "BIN", required = true)
    protected String bin;
    @XmlElement(name = "MerchantID", required = true)
    protected String merchantID;
    @XmlElement(name = "TerminalID", required = true)
    protected String terminalID;
    @XmlElement(name = "TxRefNum", required = true)
    protected String txRefNum;
    @XmlElement(name = "PCOrderNum")
    protected String pcOrderNum;
    @XmlElement(name = "PCDestZip")
    protected String pcDestZip;
    @XmlElement(name = "PCDestName")
    protected String pcDestName;
    @XmlElement(name = "PCDestAddress1")
    protected String pcDestAddress1;
    @XmlElement(name = "PCDestAddress2")
    protected String pcDestAddress2;
    @XmlElement(name = "PCDestCity")
    protected String pcDestCity;
    @XmlElement(name = "PCDestState")
    protected String pcDestState;
    @XmlElement(name = "AMEXTranAdvAddn1")
    protected String amexTranAdvAddn1;
    @XmlElement(name = "AMEXTranAdvAddn2")
    protected String amexTranAdvAddn2;
    @XmlElement(name = "AMEXTranAdvAddn3")
    protected String amexTranAdvAddn3;
    @XmlElement(name = "AMEXTranAdvAddn4")
    protected String amexTranAdvAddn4;
    @XmlElement(name = "PC3FreightAmt")
    protected String pc3FreightAmt;
    @XmlElement(name = "PC3DutyAmt")
    protected String pc3DutyAmt;
    @XmlElement(name = "PC3DestCountryCd")
    protected String pc3DestCountryCd;
    @XmlElement(name = "PC3ShipFromZip")
    protected String pc3ShipFromZip;
    @XmlElement(name = "PC3DiscAmt")
    protected String pc3DiscAmt;
    @XmlElement(name = "PC3VATtaxAmt")
    protected String pc3VATtaxAmt;
    @XmlElement(name = "PC3VATtaxRate")
    protected String pc3VATtaxRate;
    @XmlElement(name = "PC3AltTaxInd")
    protected String pc3AltTaxInd;
    @XmlElement(name = "PC3AltTaxID")
    protected String pc3AltTaxID;
    @XmlElement(name = "PC3AltTaxAmt")
    protected String pc3AltTaxAmt;
    @XmlElement(name = "PC3LineItemCount")
    protected String pc3LineItemCount;
    @XmlElement(name = "PC3LineItemArray")
    protected PC3LineItemArray pc3LineItemArray;
    @XmlElement(name = "PCardRequestorName")
    protected String pCardRequestorName;
    @XmlElement(name = "PCardLocalTaxRate")
    protected String pCardLocalTaxRate;
    @XmlElement(name = "PCardNationalTax")
    protected String pCardNationalTax;
    @XmlElement(name = "PCardPstTaxRegNumber")
    protected String pCardPstTaxRegNumber;
    @XmlElement(name = "PCardCustomerVatRegNumber")
    protected String pCardCustomerVatRegNumber;
    @XmlElement(name = "PCardMerchantVatRegNumber")
    protected String pCardMerchantVatRegNumber;
    @XmlElement(name = "PCardTotalTaxAmount")
    protected String pCardTotalTaxAmount;
    @XmlElement(name = "PCardDtlTaxAmount1Ind")
    protected String pCardDtlTaxAmount1Ind;
    @XmlElement(name = "PCardDtlTaxAmount1")
    protected String pCardDtlTaxAmount1;
    @XmlElement(name = "PCardDtlTaxAmount2Ind")
    protected String pCardDtlTaxAmount2Ind;
    @XmlElement(name = "PCardDtlTaxAmount2")
    protected String pCardDtlTaxAmount2;
    @XmlElement(name = "PinlessDebitTotalShpmnt")
    protected String pinlessDebitTotalShpmnt;
    @XmlElement(name = "AuthenticationECIInd")
    protected String authenticationECIInd;
    @XmlElement(name = "DigitalTokenCryptogram")
    protected String digitalTokenCryptogram;
    @XmlElement(name = "XID")
    protected String xid;
    @XmlElement(name = "SCATrustedMerchant")
    protected String scaTrustedMerchant;
    @XmlElement(name = "SCASecureCorporatePayment")
    protected String scaSecureCorporatePayment;
    @XmlElement(name = "SCATransactionRiskAnalysis")
    protected String scaTransactionRiskAnalysis;
    @XmlElement(name = "SCALowValuePayment")
    protected String scaLowValuePayment;
    @XmlElement(name = "SCAMerchantInitiatedTransaction")
    protected String scaMerchantInitiatedTransaction;
    @XmlElement(name = "SCARecurringPayment")
    protected String scaRecurringPayment;
    @XmlElement(name = "SCADelegation")
    protected String scaDelegation;
    @XmlElement(name = "MCProgramProtocol")
    protected String mcProgramProtocol;
    @XmlElement(name = "MCDirectoryTransID")
    protected String mcDirectoryTransID;
    @XmlElement(name = "UCAFInd")
    protected String ucafInd;

    /**
     * Gets the value of the orbitalConnectionUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalConnectionUsername() {
        return orbitalConnectionUsername;
    }

    /**
     * Sets the value of the orbitalConnectionUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalConnectionUsername(String value) {
        this.orbitalConnectionUsername = value;
    }

    /**
     * Gets the value of the orbitalConnectionPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrbitalConnectionPassword() {
        return orbitalConnectionPassword;
    }

    /**
     * Sets the value of the orbitalConnectionPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrbitalConnectionPassword(String value) {
        this.orbitalConnectionPassword = value;
    }

    /**
     * Gets the value of the orderID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderID() {
        return orderID;
    }

    /**
     * Sets the value of the orderID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderID(String value) {
        this.orderID = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the taxInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxInd() {
        return taxInd;
    }

    /**
     * Sets the value of the taxInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxInd(String value) {
        this.taxInd = value;
    }

    /**
     * Gets the value of the tax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTax() {
        return tax;
    }

    /**
     * Sets the value of the tax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTax(String value) {
        this.tax = value;
    }

    /**
     * Gets the value of the bin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIN() {
        return bin;
    }

    /**
     * Sets the value of the bin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIN(String value) {
        this.bin = value;
    }

    /**
     * Gets the value of the merchantID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantID() {
        return merchantID;
    }

    /**
     * Sets the value of the merchantID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantID(String value) {
        this.merchantID = value;
    }

    /**
     * Gets the value of the terminalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalID() {
        return terminalID;
    }

    /**
     * Sets the value of the terminalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalID(String value) {
        this.terminalID = value;
    }

    /**
     * Gets the value of the txRefNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxRefNum() {
        return txRefNum;
    }

    /**
     * Sets the value of the txRefNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxRefNum(String value) {
        this.txRefNum = value;
    }

    /**
     * Gets the value of the pcOrderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCOrderNum() {
        return pcOrderNum;
    }

    /**
     * Sets the value of the pcOrderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCOrderNum(String value) {
        this.pcOrderNum = value;
    }

    /**
     * Gets the value of the pcDestZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDestZip() {
        return pcDestZip;
    }

    /**
     * Sets the value of the pcDestZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDestZip(String value) {
        this.pcDestZip = value;
    }

    /**
     * Gets the value of the pcDestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDestName() {
        return pcDestName;
    }

    /**
     * Sets the value of the pcDestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDestName(String value) {
        this.pcDestName = value;
    }

    /**
     * Gets the value of the pcDestAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDestAddress1() {
        return pcDestAddress1;
    }

    /**
     * Sets the value of the pcDestAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDestAddress1(String value) {
        this.pcDestAddress1 = value;
    }

    /**
     * Gets the value of the pcDestAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDestAddress2() {
        return pcDestAddress2;
    }

    /**
     * Sets the value of the pcDestAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDestAddress2(String value) {
        this.pcDestAddress2 = value;
    }

    /**
     * Gets the value of the pcDestCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDestCity() {
        return pcDestCity;
    }

    /**
     * Sets the value of the pcDestCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDestCity(String value) {
        this.pcDestCity = value;
    }

    /**
     * Gets the value of the pcDestState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDestState() {
        return pcDestState;
    }

    /**
     * Sets the value of the pcDestState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDestState(String value) {
        this.pcDestState = value;
    }

    /**
     * Gets the value of the amexTranAdvAddn1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMEXTranAdvAddn1() {
        return amexTranAdvAddn1;
    }

    /**
     * Sets the value of the amexTranAdvAddn1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMEXTranAdvAddn1(String value) {
        this.amexTranAdvAddn1 = value;
    }

    /**
     * Gets the value of the amexTranAdvAddn2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMEXTranAdvAddn2() {
        return amexTranAdvAddn2;
    }

    /**
     * Sets the value of the amexTranAdvAddn2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMEXTranAdvAddn2(String value) {
        this.amexTranAdvAddn2 = value;
    }

    /**
     * Gets the value of the amexTranAdvAddn3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMEXTranAdvAddn3() {
        return amexTranAdvAddn3;
    }

    /**
     * Sets the value of the amexTranAdvAddn3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMEXTranAdvAddn3(String value) {
        this.amexTranAdvAddn3 = value;
    }

    /**
     * Gets the value of the amexTranAdvAddn4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMEXTranAdvAddn4() {
        return amexTranAdvAddn4;
    }

    /**
     * Sets the value of the amexTranAdvAddn4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMEXTranAdvAddn4(String value) {
        this.amexTranAdvAddn4 = value;
    }

    /**
     * Gets the value of the pc3FreightAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3FreightAmt() {
        return pc3FreightAmt;
    }

    /**
     * Sets the value of the pc3FreightAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3FreightAmt(String value) {
        this.pc3FreightAmt = value;
    }

    /**
     * Gets the value of the pc3DutyAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DutyAmt() {
        return pc3DutyAmt;
    }

    /**
     * Sets the value of the pc3DutyAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DutyAmt(String value) {
        this.pc3DutyAmt = value;
    }

    /**
     * Gets the value of the pc3DestCountryCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DestCountryCd() {
        return pc3DestCountryCd;
    }

    /**
     * Sets the value of the pc3DestCountryCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DestCountryCd(String value) {
        this.pc3DestCountryCd = value;
    }

    /**
     * Gets the value of the pc3ShipFromZip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3ShipFromZip() {
        return pc3ShipFromZip;
    }

    /**
     * Sets the value of the pc3ShipFromZip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3ShipFromZip(String value) {
        this.pc3ShipFromZip = value;
    }

    /**
     * Gets the value of the pc3DiscAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DiscAmt() {
        return pc3DiscAmt;
    }

    /**
     * Sets the value of the pc3DiscAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DiscAmt(String value) {
        this.pc3DiscAmt = value;
    }

    /**
     * Gets the value of the pc3VATtaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3VATtaxAmt() {
        return pc3VATtaxAmt;
    }

    /**
     * Sets the value of the pc3VATtaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3VATtaxAmt(String value) {
        this.pc3VATtaxAmt = value;
    }

    /**
     * Gets the value of the pc3VATtaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3VATtaxRate() {
        return pc3VATtaxRate;
    }

    /**
     * Sets the value of the pc3VATtaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3VATtaxRate(String value) {
        this.pc3VATtaxRate = value;
    }

    /**
     * Gets the value of the pc3AltTaxInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3AltTaxInd() {
        return pc3AltTaxInd;
    }

    /**
     * Sets the value of the pc3AltTaxInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3AltTaxInd(String value) {
        this.pc3AltTaxInd = value;
    }

    /**
     * Gets the value of the pc3AltTaxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3AltTaxID() {
        return pc3AltTaxID;
    }

    /**
     * Sets the value of the pc3AltTaxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3AltTaxID(String value) {
        this.pc3AltTaxID = value;
    }

    /**
     * Gets the value of the pc3AltTaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3AltTaxAmt() {
        return pc3AltTaxAmt;
    }

    /**
     * Sets the value of the pc3AltTaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3AltTaxAmt(String value) {
        this.pc3AltTaxAmt = value;
    }

    /**
     * Gets the value of the pc3LineItemCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3LineItemCount() {
        return pc3LineItemCount;
    }

    /**
     * Sets the value of the pc3LineItemCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3LineItemCount(String value) {
        this.pc3LineItemCount = value;
    }

    /**
     * Gets the value of the pc3LineItemArray property.
     * 
     * @return
     *     possible object is
     *     {@link PC3LineItemArray }
     *     
     */
    public PC3LineItemArray getPC3LineItemArray() {
        return pc3LineItemArray;
    }

    /**
     * Sets the value of the pc3LineItemArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link PC3LineItemArray }
     *     
     */
    public void setPC3LineItemArray(PC3LineItemArray value) {
        this.pc3LineItemArray = value;
    }

    /**
     * Gets the value of the pCardRequestorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardRequestorName() {
        return pCardRequestorName;
    }

    /**
     * Sets the value of the pCardRequestorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardRequestorName(String value) {
        this.pCardRequestorName = value;
    }

    /**
     * Gets the value of the pCardLocalTaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardLocalTaxRate() {
        return pCardLocalTaxRate;
    }

    /**
     * Sets the value of the pCardLocalTaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardLocalTaxRate(String value) {
        this.pCardLocalTaxRate = value;
    }

    /**
     * Gets the value of the pCardNationalTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardNationalTax() {
        return pCardNationalTax;
    }

    /**
     * Sets the value of the pCardNationalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardNationalTax(String value) {
        this.pCardNationalTax = value;
    }

    /**
     * Gets the value of the pCardPstTaxRegNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardPstTaxRegNumber() {
        return pCardPstTaxRegNumber;
    }

    /**
     * Sets the value of the pCardPstTaxRegNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardPstTaxRegNumber(String value) {
        this.pCardPstTaxRegNumber = value;
    }

    /**
     * Gets the value of the pCardCustomerVatRegNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardCustomerVatRegNumber() {
        return pCardCustomerVatRegNumber;
    }

    /**
     * Sets the value of the pCardCustomerVatRegNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardCustomerVatRegNumber(String value) {
        this.pCardCustomerVatRegNumber = value;
    }

    /**
     * Gets the value of the pCardMerchantVatRegNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardMerchantVatRegNumber() {
        return pCardMerchantVatRegNumber;
    }

    /**
     * Sets the value of the pCardMerchantVatRegNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardMerchantVatRegNumber(String value) {
        this.pCardMerchantVatRegNumber = value;
    }

    /**
     * Gets the value of the pCardTotalTaxAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardTotalTaxAmount() {
        return pCardTotalTaxAmount;
    }

    /**
     * Sets the value of the pCardTotalTaxAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardTotalTaxAmount(String value) {
        this.pCardTotalTaxAmount = value;
    }

    /**
     * Gets the value of the pCardDtlTaxAmount1Ind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardDtlTaxAmount1Ind() {
        return pCardDtlTaxAmount1Ind;
    }

    /**
     * Sets the value of the pCardDtlTaxAmount1Ind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardDtlTaxAmount1Ind(String value) {
        this.pCardDtlTaxAmount1Ind = value;
    }

    /**
     * Gets the value of the pCardDtlTaxAmount1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardDtlTaxAmount1() {
        return pCardDtlTaxAmount1;
    }

    /**
     * Sets the value of the pCardDtlTaxAmount1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardDtlTaxAmount1(String value) {
        this.pCardDtlTaxAmount1 = value;
    }

    /**
     * Gets the value of the pCardDtlTaxAmount2Ind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardDtlTaxAmount2Ind() {
        return pCardDtlTaxAmount2Ind;
    }

    /**
     * Sets the value of the pCardDtlTaxAmount2Ind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardDtlTaxAmount2Ind(String value) {
        this.pCardDtlTaxAmount2Ind = value;
    }

    /**
     * Gets the value of the pCardDtlTaxAmount2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCardDtlTaxAmount2() {
        return pCardDtlTaxAmount2;
    }

    /**
     * Sets the value of the pCardDtlTaxAmount2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCardDtlTaxAmount2(String value) {
        this.pCardDtlTaxAmount2 = value;
    }

    /**
     * Gets the value of the pinlessDebitTotalShpmnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinlessDebitTotalShpmnt() {
        return pinlessDebitTotalShpmnt;
    }

    /**
     * Sets the value of the pinlessDebitTotalShpmnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinlessDebitTotalShpmnt(String value) {
        this.pinlessDebitTotalShpmnt = value;
    }

    /**
     * Gets the value of the authenticationECIInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthenticationECIInd() {
        return authenticationECIInd;
    }

    /**
     * Sets the value of the authenticationECIInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthenticationECIInd(String value) {
        this.authenticationECIInd = value;
    }

    /**
     * Gets the value of the digitalTokenCryptogram property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigitalTokenCryptogram() {
        return digitalTokenCryptogram;
    }

    /**
     * Sets the value of the digitalTokenCryptogram property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigitalTokenCryptogram(String value) {
        this.digitalTokenCryptogram = value;
    }

    /**
     * Gets the value of the xid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXID() {
        return xid;
    }

    /**
     * Sets the value of the xid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXID(String value) {
        this.xid = value;
    }

    /**
     * Gets the value of the scaTrustedMerchant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCATrustedMerchant() {
        return scaTrustedMerchant;
    }

    /**
     * Sets the value of the scaTrustedMerchant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCATrustedMerchant(String value) {
        this.scaTrustedMerchant = value;
    }

    /**
     * Gets the value of the scaSecureCorporatePayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCASecureCorporatePayment() {
        return scaSecureCorporatePayment;
    }

    /**
     * Sets the value of the scaSecureCorporatePayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCASecureCorporatePayment(String value) {
        this.scaSecureCorporatePayment = value;
    }

    /**
     * Gets the value of the scaTransactionRiskAnalysis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCATransactionRiskAnalysis() {
        return scaTransactionRiskAnalysis;
    }

    /**
     * Sets the value of the scaTransactionRiskAnalysis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCATransactionRiskAnalysis(String value) {
        this.scaTransactionRiskAnalysis = value;
    }

    /**
     * Gets the value of the scaLowValuePayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCALowValuePayment() {
        return scaLowValuePayment;
    }

    /**
     * Sets the value of the scaLowValuePayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCALowValuePayment(String value) {
        this.scaLowValuePayment = value;
    }

    /**
     * Gets the value of the scaMerchantInitiatedTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCAMerchantInitiatedTransaction() {
        return scaMerchantInitiatedTransaction;
    }

    /**
     * Sets the value of the scaMerchantInitiatedTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCAMerchantInitiatedTransaction(String value) {
        this.scaMerchantInitiatedTransaction = value;
    }

    /**
     * Gets the value of the scaRecurringPayment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCARecurringPayment() {
        return scaRecurringPayment;
    }

    /**
     * Sets the value of the scaRecurringPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCARecurringPayment(String value) {
        this.scaRecurringPayment = value;
    }

    /**
     * Gets the value of the scaDelegation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCADelegation() {
        return scaDelegation;
    }

    /**
     * Sets the value of the scaDelegation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCADelegation(String value) {
        this.scaDelegation = value;
    }

    /**
     * Gets the value of the mcProgramProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCProgramProtocol() {
        return mcProgramProtocol;
    }

    /**
     * Sets the value of the mcProgramProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCProgramProtocol(String value) {
        this.mcProgramProtocol = value;
    }

    /**
     * Gets the value of the mcDirectoryTransID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCDirectoryTransID() {
        return mcDirectoryTransID;
    }

    /**
     * Sets the value of the mcDirectoryTransID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCDirectoryTransID(String value) {
        this.mcDirectoryTransID = value;
    }

    /**
     * Gets the value of the ucafInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCAFInd() {
        return ucafInd;
    }

    /**
     * Sets the value of the ucafInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCAFInd(String value) {
        this.ucafInd = value;
    }

}
