//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.medicalmine.chase.bean.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.medicalmine.chase.bean.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SettleRejectHoldingBin }
     * 
     */
    public SettleRejectHoldingBin createSettleRejectHoldingBin() {
        return new SettleRejectHoldingBin();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link AccountUpdaterType }
     * 
     */
    public AccountUpdaterType createAccountUpdaterType() {
        return new AccountUpdaterType();
    }

    /**
     * Create an instance of {@link InquiryType }
     * 
     */
    public InquiryType createInquiryType() {
        return new InquiryType();
    }

    /**
     * Create an instance of {@link NewOrderType }
     * 
     */
    public NewOrderType createNewOrderType() {
        return new NewOrderType();
    }

    /**
     * Create an instance of {@link EndOfDayType }
     * 
     */
    public EndOfDayType createEndOfDayType() {
        return new EndOfDayType();
    }

    /**
     * Create an instance of {@link FlexCacheType }
     * 
     */
    public FlexCacheType createFlexCacheType() {
        return new FlexCacheType();
    }

    /**
     * Create an instance of {@link ProfileType }
     * 
     */
    public ProfileType createProfileType() {
        return new ProfileType();
    }

    /**
     * Create an instance of {@link ReversalType }
     * 
     */
    public ReversalType createReversalType() {
        return new ReversalType();
    }

    /**
     * Create an instance of {@link MarkForCaptureType }
     * 
     */
    public MarkForCaptureType createMarkForCaptureType() {
        return new MarkForCaptureType();
    }

    /**
     * Create an instance of {@link SafetechFraudAnalysisType }
     * 
     */
    public SafetechFraudAnalysisType createSafetechFraudAnalysisType() {
        return new SafetechFraudAnalysisType();
    }

    /**
     * Create an instance of {@link FraudAnalysisType }
     * 
     */
    public FraudAnalysisType createFraudAnalysisType() {
        return new FraudAnalysisType();
    }

    /**
     * Create an instance of {@link PC3LineItemType }
     * 
     */
    public PC3LineItemType createPC3LineItemType() {
        return new PC3LineItemType();
    }

    /**
     * Create an instance of {@link SoftMerchantDescriptorsType }
     * 
     */
    public SoftMerchantDescriptorsType createSoftMerchantDescriptorsType() {
        return new SoftMerchantDescriptorsType();
    }

    /**
     * Create an instance of {@link PC3LineItemArray }
     * 
     */
    public PC3LineItemArray createPC3LineItemArray() {
        return new PC3LineItemArray();
    }

    /**
     * Create an instance of {@link BaseElementsType }
     * 
     */
    public BaseElementsType createBaseElementsType() {
        return new BaseElementsType();
    }

}
