//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PC3LineItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PC3LineItemType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PC3DtlIndex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlProdCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlQty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlUOM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlTaxAmt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlTaxRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3Dtllinetot" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlDisc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlCommCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlUnitCost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlGrossNet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlTaxType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlDiscInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlDebitInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PC3DtlDiscountRate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PC3LineItemType", propOrder = {
    "pc3DtlIndex",
    "pc3DtlDesc",
    "pc3DtlProdCd",
    "pc3DtlQty",
    "pc3DtlUOM",
    "pc3DtlTaxAmt",
    "pc3DtlTaxRate",
    "pc3Dtllinetot",
    "pc3DtlDisc",
    "pc3DtlCommCd",
    "pc3DtlUnitCost",
    "pc3DtlGrossNet",
    "pc3DtlTaxType",
    "pc3DtlDiscInd",
    "pc3DtlDebitInd",
    "pc3DtlDiscountRate"
})
public class PC3LineItemType {

    @XmlElement(name = "PC3DtlIndex")
    protected String pc3DtlIndex;
    @XmlElement(name = "PC3DtlDesc")
    protected String pc3DtlDesc;
    @XmlElement(name = "PC3DtlProdCd")
    protected String pc3DtlProdCd;
    @XmlElement(name = "PC3DtlQty")
    protected String pc3DtlQty;
    @XmlElement(name = "PC3DtlUOM")
    protected String pc3DtlUOM;
    @XmlElement(name = "PC3DtlTaxAmt")
    protected String pc3DtlTaxAmt;
    @XmlElement(name = "PC3DtlTaxRate")
    protected String pc3DtlTaxRate;
    @XmlElement(name = "PC3Dtllinetot")
    protected String pc3Dtllinetot;
    @XmlElement(name = "PC3DtlDisc")
    protected String pc3DtlDisc;
    @XmlElement(name = "PC3DtlCommCd")
    protected String pc3DtlCommCd;
    @XmlElement(name = "PC3DtlUnitCost")
    protected String pc3DtlUnitCost;
    @XmlElement(name = "PC3DtlGrossNet")
    protected String pc3DtlGrossNet;
    @XmlElement(name = "PC3DtlTaxType")
    protected String pc3DtlTaxType;
    @XmlElement(name = "PC3DtlDiscInd")
    protected String pc3DtlDiscInd;
    @XmlElement(name = "PC3DtlDebitInd")
    protected String pc3DtlDebitInd;
    @XmlElement(name = "PC3DtlDiscountRate")
    protected String pc3DtlDiscountRate;

    /**
     * Gets the value of the pc3DtlIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlIndex() {
        return pc3DtlIndex;
    }

    /**
     * Sets the value of the pc3DtlIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlIndex(String value) {
        this.pc3DtlIndex = value;
    }

    /**
     * Gets the value of the pc3DtlDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlDesc() {
        return pc3DtlDesc;
    }

    /**
     * Sets the value of the pc3DtlDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlDesc(String value) {
        this.pc3DtlDesc = value;
    }

    /**
     * Gets the value of the pc3DtlProdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlProdCd() {
        return pc3DtlProdCd;
    }

    /**
     * Sets the value of the pc3DtlProdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlProdCd(String value) {
        this.pc3DtlProdCd = value;
    }

    /**
     * Gets the value of the pc3DtlQty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlQty() {
        return pc3DtlQty;
    }

    /**
     * Sets the value of the pc3DtlQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlQty(String value) {
        this.pc3DtlQty = value;
    }

    /**
     * Gets the value of the pc3DtlUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlUOM() {
        return pc3DtlUOM;
    }

    /**
     * Sets the value of the pc3DtlUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlUOM(String value) {
        this.pc3DtlUOM = value;
    }

    /**
     * Gets the value of the pc3DtlTaxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlTaxAmt() {
        return pc3DtlTaxAmt;
    }

    /**
     * Sets the value of the pc3DtlTaxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlTaxAmt(String value) {
        this.pc3DtlTaxAmt = value;
    }

    /**
     * Gets the value of the pc3DtlTaxRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlTaxRate() {
        return pc3DtlTaxRate;
    }

    /**
     * Sets the value of the pc3DtlTaxRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlTaxRate(String value) {
        this.pc3DtlTaxRate = value;
    }

    /**
     * Gets the value of the pc3Dtllinetot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3Dtllinetot() {
        return pc3Dtllinetot;
    }

    /**
     * Sets the value of the pc3Dtllinetot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3Dtllinetot(String value) {
        this.pc3Dtllinetot = value;
    }

    /**
     * Gets the value of the pc3DtlDisc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlDisc() {
        return pc3DtlDisc;
    }

    /**
     * Sets the value of the pc3DtlDisc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlDisc(String value) {
        this.pc3DtlDisc = value;
    }

    /**
     * Gets the value of the pc3DtlCommCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlCommCd() {
        return pc3DtlCommCd;
    }

    /**
     * Sets the value of the pc3DtlCommCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlCommCd(String value) {
        this.pc3DtlCommCd = value;
    }

    /**
     * Gets the value of the pc3DtlUnitCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlUnitCost() {
        return pc3DtlUnitCost;
    }

    /**
     * Sets the value of the pc3DtlUnitCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlUnitCost(String value) {
        this.pc3DtlUnitCost = value;
    }

    /**
     * Gets the value of the pc3DtlGrossNet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlGrossNet() {
        return pc3DtlGrossNet;
    }

    /**
     * Sets the value of the pc3DtlGrossNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlGrossNet(String value) {
        this.pc3DtlGrossNet = value;
    }

    /**
     * Gets the value of the pc3DtlTaxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlTaxType() {
        return pc3DtlTaxType;
    }

    /**
     * Sets the value of the pc3DtlTaxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlTaxType(String value) {
        this.pc3DtlTaxType = value;
    }

    /**
     * Gets the value of the pc3DtlDiscInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlDiscInd() {
        return pc3DtlDiscInd;
    }

    /**
     * Sets the value of the pc3DtlDiscInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlDiscInd(String value) {
        this.pc3DtlDiscInd = value;
    }

    /**
     * Gets the value of the pc3DtlDebitInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlDebitInd() {
        return pc3DtlDebitInd;
    }

    /**
     * Sets the value of the pc3DtlDebitInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlDebitInd(String value) {
        this.pc3DtlDebitInd = value;
    }

    /**
     * Gets the value of the pc3DtlDiscountRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPC3DtlDiscountRate() {
        return pc3DtlDiscountRate;
    }

    /**
     * Sets the value of the pc3DtlDiscountRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPC3DtlDiscountRate(String value) {
        this.pc3DtlDiscountRate = value;
    }

}
