//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for valid-industry-types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="valid-industry-types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="20"/>
 *     &lt;enumeration value="EC"/>
 *     &lt;enumeration value="RC"/>
 *     &lt;enumeration value="MO"/>
 *     &lt;enumeration value="IV"/>
 *     &lt;enumeration value="IN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "valid-industry-types")
@XmlEnum
public enum ValidIndustryTypes {


    /**
     * Ecommerce transaction
     * 
     */
    EC,

    /**
     * Recurring Payment transaction
     * 
     */
    RC,

    /**
     * Mail Order Telephone Order transaction
     * 
     */
    MO,

    /**
     * Interactive Voice Response
     * 
     */
    IV,

    /**
     * Interactive Voice Response
     * 
     */
    IN;

    public String value() {
        return name();
    }

    public static ValidIndustryTypes fromValue(String v) {
        return valueOf(v);
    }

}
