//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.12 at 06:20:05 PM IST 
//


package com.medicalmine.charm.store.chase.bean.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for valid-trans-types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="valid-trans-types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="20"/>
 *     &lt;enumeration value="A"/>
 *     &lt;enumeration value="AC"/>
 *     &lt;enumeration value="F"/>
 *     &lt;enumeration value="FR"/>
 *     &lt;enumeration value="FC"/>
 *     &lt;enumeration value="R"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "valid-trans-types")
@XmlEnum
public enum ValidTransTypes {


    /**
     * Auth Only No Capture
     * 
     */
    A,

    /**
     * Auth and Capture
     * 
     */
    AC,

    /**
     * Force Auth No Capture and no online authorization
     * 
     */
    F,

    /**
     * Force Auth No Capture and no online authorization
     * 
     */
    FR,

    /**
     * Force Auth and Capture no online authorization
     * 
     */
    FC,

    /**
     * Refund and Capture no online authorization
     * 
     */
    R;

    public String value() {
        return name();
    }

    public static ValidTransTypes fromValue(String v) {
        return valueOf(v);
    }

}
